<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>PaviseShield</AssemblyName>
    <RootNamespace>PaviseShield</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
    <Optimize>true</Optimize>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <BannerlordPath Condition="'$(BannerlordPath)' == ''">E:\SteamLibrary\steamapps\common\Mount &amp; Blade II Bannerlord</BannerlordPath>
    <BannerlordBin>$(BannerlordPath)\bin\Win64_Shipping_Client</BannerlordBin>
    <BannerlordModules>$(BannerlordPath)\Modules</BannerlordModules>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(BannerlordBin)\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Core">
      <HintPath>$(BannerlordBin)\TaleWorlds.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Library">
      <HintPath>$(BannerlordBin)\TaleWorlds.Library.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(BannerlordBin)\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(BannerlordBin)\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Localization">
      <HintPath>$(BannerlordBin)\TaleWorlds.Localization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.InputSystem">
      <HintPath>$(BannerlordBin)\TaleWorlds.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.Engine">
      <HintPath>$(BannerlordBin)\TaleWorlds.Engine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TaleWorlds.DotNet">
      <HintPath>$(BannerlordBin)\TaleWorlds.DotNet.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>E:\SteamLibrary\steamapps\workshop\content\261550\3596693285\bin\Win64_Shipping_Client\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToMod" AfterTargets="Build">
    <Copy
      SourceFiles="$(OutputPath)$(AssemblyName).dll"
      DestinationFolder="$(BannerlordModules)\PaviseShield\bin\Win64_Shipping_Client"
      SkipUnchangedFiles="true"
      ContinueOnError="true"/>
  </Target>

</Project>
