using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement.Categories;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.GamepadNavigation;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Clan;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Menu.TownManagement;

namespace SandBox.GauntletUI.AutoGenerated0;

public class ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_3_ClanParties__DependendPrefab : Widget
{
	private Widget _widget;

	private ListPanel _widget_0;

	private ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_14_ClanPartiesRightPanel__DependendPrefab _widget_0_0;

	private ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_15_ClanPartiesLeftPanel__DependendPrefab _widget_0_1;

	private ClanPartyRoleSelectionPopupWidget _widget_1;

	private NavigationForcedScopeCollectionTargeter _widget_1_0;

	private NavigationScopeTargeter _widget_1_1;

	private AutoClosePopupClosingWidget _widget_1_2;

	private BrushWidget _widget_1_3;

	private NavigatableGridWidget _widget_1_3_0;

	private ClanPartiesVM _datasource_Root;

	private ClanPartyItemVM _datasource_Root_CurrentSelectedParty;

	private ClanRoleItemVM _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;

	private MBBindingList<ClanRoleMemberItemVM> _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members;

	public ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_3_ClanParties__DependendPrefab(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new ListPanel(base.Context);
		_widget.AddChild(_widget_0);
		_widget_0_0 = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_14_ClanPartiesRightPanel__DependendPrefab(base.Context);
		_widget_0.AddChild(_widget_0_0);
		_widget_0_0.CreateWidgets();
		_widget_0_1 = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_15_ClanPartiesLeftPanel__DependendPrefab(base.Context);
		_widget_0.AddChild(_widget_0_1);
		_widget_0_1.CreateWidgets();
		_widget_1 = new ClanPartyRoleSelectionPopupWidget(base.Context);
		_widget.AddChild(_widget_1);
		_widget_1_0 = new NavigationForcedScopeCollectionTargeter(base.Context);
		_widget_1.AddChild(_widget_1_0);
		_widget_1_1 = new NavigationScopeTargeter(base.Context);
		_widget_1.AddChild(_widget_1_1);
		_widget_1_2 = new AutoClosePopupClosingWidget(base.Context);
		_widget_1.AddChild(_widget_1_2);
		_widget_1_3 = new BrushWidget(base.Context);
		_widget_1.AddChild(_widget_1_3);
		_widget_1_3_0 = new NavigatableGridWidget(base.Context);
		_widget_1_3.AddChild(_widget_1_3_0);
	}

	public void SetIds()
	{
		base.Id = "ClanPartiesWidget";
		_widget_0_0.SetIds();
		_widget_0_1.SetIds();
		_widget_1.Id = "PartyRoleSelectionWidget";
		_widget_1_3.Id = "HeroMembersListPanelBackground";
		_widget_1_3_0.Id = "HeroMembersListPanel";
	}

	public void SetAttributes()
	{
		base.WidthSizePolicy = SizePolicy.StretchToParent;
		base.HeightSizePolicy = SizePolicy.StretchToParent;
		base.DoNotAcceptEvents = true;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.StackLayout.LayoutMethod = LayoutMethod.HorizontalRightToLeft;
		_widget_0.DoNotAcceptEvents = true;
		_widget_0_0.SetAttributes();
		_widget_0_1.SetAttributes();
		_widget_1.WidthSizePolicy = SizePolicy.Fixed;
		_widget_1.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1.HorizontalAlignment = HorizontalAlignment.Right;
		_widget_1.VerticalAlignment = VerticalAlignment.Center;
		_widget_1.SuggestedWidth = 320f;
		_widget_1_0.CollectionParent = _widget_1;
		_widget_1_1.ScopeID = "RoleSelectionPopupScope";
		_widget_1_1.ScopeMovements = GamepadNavigationTypes.Horizontal;
		_widget_1_1.AlternateScopeMovements = GamepadNavigationTypes.Vertical;
		_widget_1_1.AlternateMovementStepSize = 5;
		_widget_1_1.ScopeParent = _widget_1;
		_widget_1_2.Target = _widget_1_3_0;
		_widget_1_2.IncludeChildren = true;
		_widget_1_2.IncludeTarget = false;
		_widget_1_3.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1_3.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1_3.VerticalAlignment = VerticalAlignment.Bottom;
		_widget_1_3.Brush = base.Context.GetBrush("SPClan.RoleSelectionPopup.Background");
		_widget_1_3_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1_3_0.HeightSizePolicy = SizePolicy.CoverChildren;
		_widget_1_3_0.DefaultCellWidth = 49f;
		_widget_1_3_0.DefaultCellHeight = 46f;
		_widget_1_3_0.HorizontalAlignment = HorizontalAlignment.Left;
		_widget_1_3_0.ColumnCount = 5;
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_widget_0_0.DestroyDataSource();
		_widget_0_1.DestroyDataSource();
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
		_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
		_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
		_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
		_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
		_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
		_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
		_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
		_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
		if (_datasource_Root_CurrentSelectedParty != null)
		{
			_datasource_Root_CurrentSelectedParty.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty;
			_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection != null)
			{
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
				{
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged -= OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
					for (int num = _widget_1_3_0.ChildCount - 1; num >= 0; num--)
					{
						Widget child = _widget_1_3_0.GetChild(num);
						((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child).OnBeforeRemovedChild(child);
						((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)_widget_1_3_0.GetChild(num)).DestroyDataSource();
					}
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = null;
				}
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = null;
			}
			_datasource_Root_CurrentSelectedParty = null;
		}
		_datasource_Root = null;
	}

	public void SetDataSource(ClanPartiesVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsSelected = _widget.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root_CurrentSelectedParty.IsRoleSelectionPopupVisible = _widget_1.IsVisible;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "CurrentSelectedParty")
		{
			RefreshDataSource_datasource_Root_CurrentSelectedParty(_datasource_Root.CurrentSelectedParty);
		}
		else if (propertyName == "IsSelected")
		{
			_widget.IsVisible = _datasource_Root.IsSelected;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty(string propertyName)
	{
		if (propertyName == "LastOpenedRoleSelection")
		{
			RefreshDataSource_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(_datasource_Root_CurrentSelectedParty.LastOpenedRoleSelection);
		}
		else if (propertyName == "IsRoleSelectionPopupVisible")
		{
			_widget_1.IsVisible = _datasource_Root_CurrentSelectedParty.IsRoleSelectionPopupVisible;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(string propertyName)
	{
		if (propertyName == "Members")
		{
			RefreshDataSource_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members(_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.Members);
		}
	}

	public void OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged(object sender, TaleWorlds.Library.ListChangedEventArgs e)
	{
		switch (e.ListChangedType)
		{
		case TaleWorlds.Library.ListChangedType.Reset:
		{
			for (int num = _widget_1_3_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child3 = _widget_1_3_0.GetChild(num);
				((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child3).OnBeforeRemovedChild(child3);
				Widget child4 = _widget_1_3_0.GetChild(num);
				((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child4).SetDataSource(null);
				_widget_1_3_0.RemoveChild(child4);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.Sorted:
		{
			for (int i = 0; i < _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.Count; i++)
			{
				ClanRoleMemberItemVM bindingObject = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members[i];
				_widget_1_3_0.FindChild((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject).SetSiblingIndex(i);
			}
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemAdded:
		{
			ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate(base.Context);
			GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate);
			ClanRoleMemberItemVM dataSource = (ClanRoleMemberItemVM)(generatedWidgetData.Data = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members[e.NewIndex]);
			clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.AddComponent(generatedWidgetData);
			_widget_1_3_0.AddChildAtIndex(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate, e.NewIndex);
			clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.CreateWidgets();
			clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetIds();
			clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetAttributes();
			clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetDataSource(dataSource);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemBeforeDeleted:
		{
			Widget child2 = _widget_1_3_0.GetChild(e.NewIndex);
			((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child2).OnBeforeRemovedChild(child2);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemDeleted:
		{
			Widget child = _widget_1_3_0.GetChild(e.NewIndex);
			((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child).SetDataSource(null);
			_widget_1_3_0.RemoveChild(child);
			break;
		}
		case TaleWorlds.Library.ListChangedType.ItemChanged:
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(ClanPartiesVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_widget_0_0.SetDataSource(null);
			_widget_0_1.SetDataSource(null);
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.PropertyChanged -= PropertyChangedListenerOf_widget;
			_widget.boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			_widget.floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			_widget.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			_widget.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			_widget.doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			_widget.intPropertyChanged -= intPropertyChangedListenerOf_widget;
			_widget.uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			_widget.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			if (_datasource_Root_CurrentSelectedParty != null)
			{
				_datasource_Root_CurrentSelectedParty.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty;
				_datasource_Root_CurrentSelectedParty.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty;
				_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
				_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
				_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
				_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
				_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
				_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
				_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
				_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
				_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
				if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection != null)
				{
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
					if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
					{
						_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged -= OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
						for (int num = _widget_1_3_0.ChildCount - 1; num >= 0; num--)
						{
							Widget child = _widget_1_3_0.GetChild(num);
							((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child).OnBeforeRemovedChild(child);
							Widget child2 = _widget_1_3_0.GetChild(num);
							((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child2).SetDataSource(null);
							_widget_1_3_0.RemoveChild(child2);
						}
						_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = null;
					}
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = null;
				}
				_datasource_Root_CurrentSelectedParty = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget.IsVisible = _datasource_Root.IsSelected;
		_widget.PropertyChanged += PropertyChangedListenerOf_widget;
		_widget.boolPropertyChanged += boolPropertyChangedListenerOf_widget;
		_widget.floatPropertyChanged += floatPropertyChangedListenerOf_widget;
		_widget.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
		_widget.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
		_widget.doublePropertyChanged += doublePropertyChangedListenerOf_widget;
		_widget.intPropertyChanged += intPropertyChangedListenerOf_widget;
		_widget.uintPropertyChanged += uintPropertyChangedListenerOf_widget;
		_widget.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
		_datasource_Root_CurrentSelectedParty = _datasource_Root.CurrentSelectedParty;
		if (_datasource_Root_CurrentSelectedParty != null)
		{
			_datasource_Root_CurrentSelectedParty.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty;
			_widget_1.IsVisible = _datasource_Root_CurrentSelectedParty.IsRoleSelectionPopupVisible;
			_widget_1.PropertyChanged += PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = _datasource_Root_CurrentSelectedParty.LastOpenedRoleSelection;
			if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection != null)
			{
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.Members;
				if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
				{
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged += OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
					for (int i = 0; i < _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.Count; i++)
					{
						ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate(base.Context);
						GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate);
						ClanRoleMemberItemVM dataSource = (ClanRoleMemberItemVM)(generatedWidgetData.Data = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members[i]);
						clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.AddComponent(generatedWidgetData);
						_widget_1_3_0.AddChildAtIndex(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate, i);
						clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.CreateWidgets();
						clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetIds();
						clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetAttributes();
						clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetDataSource(dataSource);
					}
				}
			}
		}
		_widget_0_0.SetDataSource(_datasource_Root);
		_widget_0_1.SetDataSource(_datasource_Root);
	}

	private void RefreshDataSource_datasource_Root_CurrentSelectedParty(ClanPartyItemVM newDataSource)
	{
		if (_datasource_Root_CurrentSelectedParty != null)
		{
			_datasource_Root_CurrentSelectedParty.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty;
			_datasource_Root_CurrentSelectedParty.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty;
			_widget_1.PropertyChanged -= PropertyChangedListenerOf_widget_1;
			_widget_1.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			_widget_1.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			_widget_1.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			_widget_1.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			_widget_1.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			_widget_1.intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			_widget_1.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			_widget_1.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection != null)
			{
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
				if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
				{
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged -= OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
					for (int num = _widget_1_3_0.ChildCount - 1; num >= 0; num--)
					{
						Widget child = _widget_1_3_0.GetChild(num);
						((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child).OnBeforeRemovedChild(child);
						Widget child2 = _widget_1_3_0.GetChild(num);
						((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child2).SetDataSource(null);
						_widget_1_3_0.RemoveChild(child2);
					}
					_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = null;
				}
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = null;
			}
			_datasource_Root_CurrentSelectedParty = null;
		}
		_datasource_Root_CurrentSelectedParty = newDataSource;
		_datasource_Root_CurrentSelectedParty = _datasource_Root.CurrentSelectedParty;
		if (_datasource_Root_CurrentSelectedParty == null)
		{
			return;
		}
		_datasource_Root_CurrentSelectedParty.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty;
		_datasource_Root_CurrentSelectedParty.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty;
		_widget_1.IsVisible = _datasource_Root_CurrentSelectedParty.IsRoleSelectionPopupVisible;
		_widget_1.PropertyChanged += PropertyChangedListenerOf_widget_1;
		_widget_1.boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
		_widget_1.floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
		_widget_1.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
		_widget_1.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
		_widget_1.doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
		_widget_1.intPropertyChanged += intPropertyChangedListenerOf_widget_1;
		_widget_1.uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
		_widget_1.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = _datasource_Root_CurrentSelectedParty.LastOpenedRoleSelection;
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection == null)
		{
			return;
		}
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.Members;
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
		{
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged += OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
			for (int i = 0; i < _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.Count; i++)
			{
				ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate);
				ClanRoleMemberItemVM dataSource = (ClanRoleMemberItemVM)(generatedWidgetData.Data = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members[i]);
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_1_3_0.AddChildAtIndex(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate, i);
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.CreateWidgets();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetIds();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetAttributes();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection(ClanRoleItemVM newDataSource)
	{
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection != null)
		{
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
			if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
			{
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged -= OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
				for (int num = _widget_1_3_0.ChildCount - 1; num >= 0; num--)
				{
					Widget child = _widget_1_3_0.GetChild(num);
					((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child).OnBeforeRemovedChild(child);
					Widget child2 = _widget_1_3_0.GetChild(num);
					((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child2).SetDataSource(null);
					_widget_1_3_0.RemoveChild(child2);
				}
				_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = null;
			}
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = null;
		}
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = newDataSource;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection = _datasource_Root_CurrentSelectedParty.LastOpenedRoleSelection;
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection == null)
		{
			return;
		}
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.Members;
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
		{
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged += OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
			for (int i = 0; i < _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.Count; i++)
			{
				ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate);
				ClanRoleMemberItemVM dataSource = (ClanRoleMemberItemVM)(generatedWidgetData.Data = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members[i]);
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_1_3_0.AddChildAtIndex(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate, i);
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.CreateWidgets();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetIds();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetAttributes();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members(MBBindingList<ClanRoleMemberItemVM> newDataSource)
	{
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
		{
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged -= OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
			for (int num = _widget_1_3_0.ChildCount - 1; num >= 0; num--)
			{
				Widget child = _widget_1_3_0.GetChild(num);
				((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child).OnBeforeRemovedChild(child);
				Widget child2 = _widget_1_3_0.GetChild(num);
				((ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate)child2).SetDataSource(null);
				_widget_1_3_0.RemoveChild(child2);
			}
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = null;
		}
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = newDataSource;
		_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection.Members;
		if (_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members != null)
		{
			_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.ListChanged += OnList_datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_MembersChanged;
			for (int i = 0; i < _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members.Count; i++)
			{
				ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate = new ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate(base.Context);
				GeneratedWidgetData generatedWidgetData = new GeneratedWidgetData(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate);
				ClanRoleMemberItemVM dataSource = (ClanRoleMemberItemVM)(generatedWidgetData.Data = _datasource_Root_CurrentSelectedParty_LastOpenedRoleSelection_Members[i]);
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.AddComponent(generatedWidgetData);
				_widget_1_3_0.AddChildAtIndex(clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate, i);
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.CreateWidgets();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetIds();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetAttributes();
				clanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}
}
