using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;

namespace TaleWorlds.CampaignSystem.MapEvents;

public class ForceVolunteersEventComponent : MapEventComponent
{
	public override MapEvent.PowerCalculationContext SimulationContext
	{
		get
		{
			if (!base.MapEvent.InvolvedParties.Any((PartyBase x) => x.IsMobile && x.MobileParty.IsCurrentlyAtSea))
			{
				return MapEvent.PowerCalculationContext.Village;
			}
			return MapEvent.PowerCalculationContext.NavalRaid;
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsForceVolunteersEventComponent(object o, List<object> collectedObjects)
	{
		((ForceVolunteersEventComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected ForceVolunteersEventComponent(MapEvent mapEvent)
		: base(mapEvent)
	{
	}

	public static ForceVolunteersEventComponent CreateForceSuppliesEvent(PartyBase attackerParty, PartyBase defenderParty)
	{
		MapEvent mapEvent = new MapEvent();
		ForceVolunteersEventComponent forceVolunteersEventComponent = new ForceVolunteersEventComponent(mapEvent);
		mapEvent.Initialize(attackerParty, defenderParty, forceVolunteersEventComponent, MapEvent.BattleTypes.IsForcingVolunteers);
		if (defenderParty.Settlement?.MilitiaPartyComponent != null)
		{
			defenderParty.Settlement.MilitiaPartyComponent.MobileParty.MapEventSide = mapEvent.DefenderSide;
		}
		Campaign.Current.MapEventManager.OnMapEventCreated(mapEvent);
		return forceVolunteersEventComponent;
	}

	public static ForceVolunteersEventComponent CreateComponentForOldSaves(MapEvent mapEvent)
	{
		return new ForceVolunteersEventComponent(mapEvent);
	}

	protected override void OnInitialize()
	{
		ChangeVillageStateAction.ApplyBySettingToBeingForcedForVolunteers(base.MapEvent.MapEventSettlement, base.MapEvent.AttackerSide.LeaderParty.MobileParty);
	}

	protected override void OnBeforeFinalize()
	{
		CampaignEventDispatcher.Instance.ForceVolunteersCompleted((base.MapEvent.BattleState == BattleState.AttackerVictory) ? BattleSideEnum.Attacker : BattleSideEnum.Defender, this);
	}

	protected override void OnFinalize()
	{
		ChangeVillageStateAction.ApplyBySettingToNormal(base.MapEvent.MapEventSettlement);
	}
}
