using System;
using System.IO;
using System.Security.Cryptography;

namespace Mono.CompilerServices.SymbolWriter
{
	// Token: 0x02000343 RID: 835
	internal class SourceFileEntry
	{
		// Token: 0x1700056E RID: 1390
		// (get) Token: 0x0600154E RID: 5454 RVA: 0x0004350F File Offset: 0x0004170F
		public static int Size
		{
			get
			{
				return 8;
			}
		}

		// Token: 0x0600154F RID: 5455 RVA: 0x000438B9 File Offset: 0x00041AB9
		public SourceFileEntry(MonoSymbolFile file, string file_name)
		{
			this.file = file;
			this.file_name = file_name;
			this.Index = file.AddSource(this);
			this.creating = true;
		}

		// Token: 0x06001550 RID: 5456 RVA: 0x000438E3 File Offset: 0x00041AE3
		public SourceFileEntry(MonoSymbolFile file, string sourceFile, byte[] guid, byte[] checksum)
			: this(file, sourceFile, sourceFile, guid, checksum)
		{
		}

		// Token: 0x06001551 RID: 5457 RVA: 0x000438F1 File Offset: 0x00041AF1
		public SourceFileEntry(MonoSymbolFile file, string fileName, string sourceFile, byte[] guid, byte[] checksum)
			: this(file, fileName)
		{
			this.guid = guid;
			this.hash = checksum;
			this.sourceFile = sourceFile;
		}

		// Token: 0x1700056F RID: 1391
		// (get) Token: 0x06001552 RID: 5458 RVA: 0x00043912 File Offset: 0x00041B12
		public byte[] Checksum
		{
			get
			{
				return this.hash;
			}
		}

		// Token: 0x06001553 RID: 5459 RVA: 0x0004391C File Offset: 0x00041B1C
		internal void WriteData(MyBinaryWriter bw)
		{
			this.DataOffset = (int)bw.BaseStream.Position;
			bw.Write(this.file_name);
			if (this.guid == null)
			{
				this.guid = new byte[16];
			}
			if (this.hash == null)
			{
				try
				{
					using (FileStream fileStream = new FileStream(this.sourceFile, FileMode.Open, FileAccess.Read))
					{
						MD5 md = MD5.Create();
						this.hash = md.ComputeHash(fileStream);
					}
				}
				catch
				{
					this.hash = new byte[16];
				}
			}
			bw.Write(this.guid);
			bw.Write(this.hash);
			bw.Write((this.auto_generated > false) ? 1 : 0);
		}

		// Token: 0x06001554 RID: 5460 RVA: 0x000439E8 File Offset: 0x00041BE8
		internal void Write(BinaryWriter bw)
		{
			bw.Write(this.Index);
			bw.Write(this.DataOffset);
		}

		// Token: 0x06001555 RID: 5461 RVA: 0x00043A04 File Offset: 0x00041C04
		internal SourceFileEntry(MonoSymbolFile file, MyBinaryReader reader)
		{
			this.file = file;
			this.Index = reader.ReadInt32();
			this.DataOffset = reader.ReadInt32();
			int num = (int)reader.BaseStream.Position;
			reader.BaseStream.Position = (long)this.DataOffset;
			this.sourceFile = (this.file_name = reader.ReadString());
			this.guid = reader.ReadBytes(16);
			this.hash = reader.ReadBytes(16);
			this.auto_generated = reader.ReadByte() == 1;
			reader.BaseStream.Position = (long)num;
		}

		// Token: 0x17000570 RID: 1392
		// (get) Token: 0x06001556 RID: 5462 RVA: 0x00043AA2 File Offset: 0x00041CA2
		// (set) Token: 0x06001557 RID: 5463 RVA: 0x00043AAA File Offset: 0x00041CAA
		public string FileName
		{
			get
			{
				return this.file_name;
			}
			set
			{
				this.file_name = value;
			}
		}

		// Token: 0x17000571 RID: 1393
		// (get) Token: 0x06001558 RID: 5464 RVA: 0x00043AB3 File Offset: 0x00041CB3
		public bool AutoGenerated
		{
			get
			{
				return this.auto_generated;
			}
		}

		// Token: 0x06001559 RID: 5465 RVA: 0x00043ABB File Offset: 0x00041CBB
		public void SetAutoGenerated()
		{
			if (!this.creating)
			{
				throw new InvalidOperationException();
			}
			this.auto_generated = true;
			this.file.OffsetTable.FileFlags |= OffsetTable.Flags.IsAspxSource;
		}

		// Token: 0x0600155A RID: 5466 RVA: 0x00043AEC File Offset: 0x00041CEC
		public bool CheckChecksum()
		{
			bool flag;
			try
			{
				using (FileStream fileStream = new FileStream(this.sourceFile, FileMode.Open))
				{
					byte[] array = MD5.Create().ComputeHash(fileStream);
					for (int i = 0; i < 16; i++)
					{
						if (array[i] != this.hash[i])
						{
							return false;
						}
					}
					flag = true;
				}
			}
			catch
			{
				flag = false;
			}
			return flag;
		}

		// Token: 0x0600155B RID: 5467 RVA: 0x00043B60 File Offset: 0x00041D60
		public override string ToString()
		{
			return string.Format("SourceFileEntry ({0}:{1})", this.Index, this.DataOffset);
		}

		// Token: 0x04000AD0 RID: 2768
		public readonly int Index;

		// Token: 0x04000AD1 RID: 2769
		private int DataOffset;

		// Token: 0x04000AD2 RID: 2770
		private MonoSymbolFile file;

		// Token: 0x04000AD3 RID: 2771
		private string file_name;

		// Token: 0x04000AD4 RID: 2772
		private byte[] guid;

		// Token: 0x04000AD5 RID: 2773
		private byte[] hash;

		// Token: 0x04000AD6 RID: 2774
		private bool creating;

		// Token: 0x04000AD7 RID: 2775
		private bool auto_generated;

		// Token: 0x04000AD8 RID: 2776
		private readonly string sourceFile;
	}
}
