using System;
using System.ComponentModel;
using System.Numerics;
using NavalDLC.GauntletUI.Widgets.Widgets;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace NavalDLC.GauntletUI.AutoGenerated
{
	// Token: 0x0200001D RID: 29
	public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_27_PortUpgradePieceVisuals__DependendPrefab : Widget
	{
		// Token: 0x06000D15 RID: 3349 RVA: 0x00063D4F File Offset: 0x00061F4F
		public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_27_PortUpgradePieceVisuals__DependendPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06000D16 RID: 3350 RVA: 0x00063D58 File Offset: 0x00061F58
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new BrushWidget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new BrushWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_2 = new BrushWidget(base.Context);
			this._widget.AddChild(this._widget_2);
			this._widget_3 = new BrushWidget(base.Context);
			this._widget.AddChild(this._widget_3);
			this._widget_4 = new PortPieceImageBrushWidget(base.Context);
			this._widget.AddChild(this._widget_4);
			this._widget_5 = new Widget(base.Context);
			this._widget.AddChild(this._widget_5);
			this._widget_6 = new Widget(base.Context);
			this._widget.AddChild(this._widget_6);
			this._widget_6_0 = new BrushWidget(base.Context);
			this._widget_6.AddChild(this._widget_6_0);
			this._widget_6_1 = new BrushWidget(base.Context);
			this._widget_6.AddChild(this._widget_6_1);
			this._widget_6_2 = new BrushWidget(base.Context);
			this._widget_6.AddChild(this._widget_6_2);
			this._widget_6_3 = new BrushWidget(base.Context);
			this._widget_6.AddChild(this._widget_6_3);
			this._widget_7 = new Widget(base.Context);
			this._widget.AddChild(this._widget_7);
			this._widget_7_0 = new BrushWidget(base.Context);
			this._widget_7.AddChild(this._widget_7_0);
			this._widget_7_1 = new BrushWidget(base.Context);
			this._widget_7.AddChild(this._widget_7_1);
			this._widget_7_2 = new BrushWidget(base.Context);
			this._widget_7.AddChild(this._widget_7_2);
			this._widget_7_3 = new BrushWidget(base.Context);
			this._widget_7.AddChild(this._widget_7_3);
		}

		// Token: 0x06000D17 RID: 3351 RVA: 0x00063F8C File Offset: 0x0006218C
		public void SetIds()
		{
		}

		// Token: 0x06000D18 RID: 3352 RVA: 0x00063F90 File Offset: 0x00062190
		public void SetAttributes()
		{
			base.WidthSizePolicy = 1;
			base.HeightSizePolicy = 1;
			base.UpdateChildrenStates = true;
			this._widget_0.WidthSizePolicy = 1;
			this._widget_0.HeightSizePolicy = 1;
			this._widget_0.Brush = base.Context.GetBrush("Port.Slot.Button.Background.Bronze");
			this._widget_1.WidthSizePolicy = 1;
			this._widget_1.HeightSizePolicy = 1;
			this._widget_1.Brush = base.Context.GetBrush("Port.Slot.Button.Background.Silver");
			this._widget_2.WidthSizePolicy = 1;
			this._widget_2.HeightSizePolicy = 1;
			this._widget_2.Brush = base.Context.GetBrush("Port.Slot.Button.Background.Gold");
			this._widget_3.WidthSizePolicy = 1;
			this._widget_3.HeightSizePolicy = 1;
			this._widget_3.Brush = base.Context.GetBrush("Port.Slot.Button.Background.Diamond");
			this._widget_4.WidthSizePolicy = 1;
			this._widget_4.HeightSizePolicy = 1;
			this._widget_4.MarginLeft = 2f;
			this._widget_4.MarginRight = 2f;
			this._widget_4.MarginTop = 2f;
			this._widget_4.MarginBottom = 2f;
			this._widget_4.Brush = base.Context.GetBrush("Port.ShipUpgrade.Image");
			this._widget_5.WidthSizePolicy = 1;
			this._widget_5.HeightSizePolicy = 1;
			this._widget_5.MarginLeft = 10f;
			this._widget_5.MarginRight = 10f;
			this._widget_5.MarginTop = 10f;
			this._widget_5.MarginBottom = 10f;
			this._widget_5.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\question_mark_with_shadow");
			this._widget_5.Color = new Color(0.5333334f, 0.5333334f, 0.5333334f, 0.6901961f);
			this._widget_5.ColorFactor = 0.6f;
			this._widget_6.WidthSizePolicy = 1;
			this._widget_6.HeightSizePolicy = 1;
			this._widget_6.UpdateChildrenStates = true;
			this._widget_6.IsHidden = true;
			this._widget_6_0.WidthSizePolicy = 1;
			this._widget_6_0.HeightSizePolicy = 1;
			this._widget_6_0.Brush = base.Context.GetBrush("Port.Slot.Button.Frame.Bronze");
			this._widget_6_1.WidthSizePolicy = 1;
			this._widget_6_1.HeightSizePolicy = 1;
			this._widget_6_1.Brush = base.Context.GetBrush("Port.Slot.Button.Frame.Silver");
			this._widget_6_2.WidthSizePolicy = 1;
			this._widget_6_2.HeightSizePolicy = 1;
			this._widget_6_2.Brush = base.Context.GetBrush("Port.Slot.Button.Frame.Gold");
			this._widget_6_3.WidthSizePolicy = 1;
			this._widget_6_3.HeightSizePolicy = 1;
			this._widget_6_3.Brush = base.Context.GetBrush("Port.Slot.Button.Frame.Diamond");
			this._widget_7.WidthSizePolicy = 1;
			this._widget_7.HeightSizePolicy = 1;
			this._widget_7.UpdateChildrenStates = true;
			this._widget_7.IsVisible = true;
			this._widget_7_0.WidthSizePolicy = 1;
			this._widget_7_0.HeightSizePolicy = 1;
			this._widget_7_0.Brush = base.Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Bronze");
			this._widget_7_1.WidthSizePolicy = 1;
			this._widget_7_1.HeightSizePolicy = 1;
			this._widget_7_1.Brush = base.Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Silver");
			this._widget_7_2.WidthSizePolicy = 1;
			this._widget_7_2.HeightSizePolicy = 1;
			this._widget_7_2.Brush = base.Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Gold");
			this._widget_7_3.WidthSizePolicy = 1;
			this._widget_7_3.HeightSizePolicy = 1;
			this._widget_7_3.Brush = base.Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Diamond");
		}

		// Token: 0x06000D19 RID: 3353 RVA: 0x00064398 File Offset: 0x00062598
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
				this._widget_4.PropertyChanged -= this.PropertyChangedListenerOf_widget_4;
				this._widget_4.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_4;
				this._widget_4.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_4;
				this._widget_4.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_4;
				this._widget_4.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_4;
				this._widget_4.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_4;
				this._widget_4.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_4;
				this._widget_4.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_4;
				this._widget_4.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_4;
				this._widget_5.PropertyChanged -= this.PropertyChangedListenerOf_widget_5;
				this._widget_5.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5;
				this._widget_5.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5;
				this._widget_5.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5;
				this._widget_5.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5;
				this._widget_5.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5;
				this._widget_5.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5;
				this._widget_5.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5;
				this._widget_5.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5;
				this._widget_6_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_0;
				this._widget_6_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_1;
				this._widget_6_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_2;
				this._widget_6_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_3;
				this._widget_7_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_0;
				this._widget_7_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_1;
				this._widget_7_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_2;
				this._widget_7_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_3;
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000D1A RID: 3354 RVA: 0x00064FD8 File Offset: 0x000631D8
		public void SetDataSource(ShipUpgradePieceBaseVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000D1B RID: 3355 RVA: 0x00064FE1 File Offset: 0x000631E1
		private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D1C RID: 3356 RVA: 0x00064FEA File Offset: 0x000631EA
		private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D1D RID: 3357 RVA: 0x00064FF3 File Offset: 0x000631F3
		private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D1E RID: 3358 RVA: 0x00064FFC File Offset: 0x000631FC
		private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D1F RID: 3359 RVA: 0x00065005 File Offset: 0x00063205
		private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D20 RID: 3360 RVA: 0x0006500E File Offset: 0x0006320E
		private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D21 RID: 3361 RVA: 0x00065017 File Offset: 0x00063217
		private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D22 RID: 3362 RVA: 0x00065020 File Offset: 0x00063220
		private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D23 RID: 3363 RVA: 0x00065029 File Offset: 0x00063229
		private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_0(propertyName);
		}

		// Token: 0x06000D24 RID: 3364 RVA: 0x00065032 File Offset: 0x00063232
		private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsBronzeTier = this._widget_0.IsVisible;
				return;
			}
		}

		// Token: 0x06000D25 RID: 3365 RVA: 0x00065058 File Offset: 0x00063258
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D26 RID: 3366 RVA: 0x00065061 File Offset: 0x00063261
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D27 RID: 3367 RVA: 0x0006506A File Offset: 0x0006326A
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D28 RID: 3368 RVA: 0x00065073 File Offset: 0x00063273
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D29 RID: 3369 RVA: 0x0006507C File Offset: 0x0006327C
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D2A RID: 3370 RVA: 0x00065085 File Offset: 0x00063285
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D2B RID: 3371 RVA: 0x0006508E File Offset: 0x0006328E
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D2C RID: 3372 RVA: 0x00065097 File Offset: 0x00063297
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D2D RID: 3373 RVA: 0x000650A0 File Offset: 0x000632A0
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000D2E RID: 3374 RVA: 0x000650A9 File Offset: 0x000632A9
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsSilverTier = this._widget_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000D2F RID: 3375 RVA: 0x000650CF File Offset: 0x000632CF
		private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D30 RID: 3376 RVA: 0x000650D8 File Offset: 0x000632D8
		private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D31 RID: 3377 RVA: 0x000650E1 File Offset: 0x000632E1
		private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D32 RID: 3378 RVA: 0x000650EA File Offset: 0x000632EA
		private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D33 RID: 3379 RVA: 0x000650F3 File Offset: 0x000632F3
		private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D34 RID: 3380 RVA: 0x000650FC File Offset: 0x000632FC
		private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D35 RID: 3381 RVA: 0x00065105 File Offset: 0x00063305
		private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D36 RID: 3382 RVA: 0x0006510E File Offset: 0x0006330E
		private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D37 RID: 3383 RVA: 0x00065117 File Offset: 0x00063317
		private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000D38 RID: 3384 RVA: 0x00065120 File Offset: 0x00063320
		private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsGoldTier = this._widget_2.IsVisible;
				return;
			}
		}

		// Token: 0x06000D39 RID: 3385 RVA: 0x00065146 File Offset: 0x00063346
		private void PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D3A RID: 3386 RVA: 0x0006514F File Offset: 0x0006334F
		private void boolPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D3B RID: 3387 RVA: 0x00065158 File Offset: 0x00063358
		private void floatPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D3C RID: 3388 RVA: 0x00065161 File Offset: 0x00063361
		private void Vec2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D3D RID: 3389 RVA: 0x0006516A File Offset: 0x0006336A
		private void Vector2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D3E RID: 3390 RVA: 0x00065173 File Offset: 0x00063373
		private void doublePropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D3F RID: 3391 RVA: 0x0006517C File Offset: 0x0006337C
		private void intPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D40 RID: 3392 RVA: 0x00065185 File Offset: 0x00063385
		private void uintPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D41 RID: 3393 RVA: 0x0006518E File Offset: 0x0006338E
		private void ColorPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_3(propertyName);
		}

		// Token: 0x06000D42 RID: 3394 RVA: 0x00065197 File Offset: 0x00063397
		private void HandleWidgetPropertyChangeOf_widget_3(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsDiamondTier = this._widget_3.IsVisible;
				return;
			}
		}

		// Token: 0x06000D43 RID: 3395 RVA: 0x000651BD File Offset: 0x000633BD
		private void PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D44 RID: 3396 RVA: 0x000651C6 File Offset: 0x000633C6
		private void boolPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D45 RID: 3397 RVA: 0x000651CF File Offset: 0x000633CF
		private void floatPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D46 RID: 3398 RVA: 0x000651D8 File Offset: 0x000633D8
		private void Vec2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D47 RID: 3399 RVA: 0x000651E1 File Offset: 0x000633E1
		private void Vector2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D48 RID: 3400 RVA: 0x000651EA File Offset: 0x000633EA
		private void doublePropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D49 RID: 3401 RVA: 0x000651F3 File Offset: 0x000633F3
		private void intPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D4A RID: 3402 RVA: 0x000651FC File Offset: 0x000633FC
		private void uintPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D4B RID: 3403 RVA: 0x00065205 File Offset: 0x00063405
		private void ColorPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_4(propertyName);
		}

		// Token: 0x06000D4C RID: 3404 RVA: 0x00065210 File Offset: 0x00063410
		private void HandleWidgetPropertyChangeOf_widget_4(string propertyName)
		{
			if (propertyName == "Identifier")
			{
				this._datasource_Root.Identifier = this._widget_4.Identifier;
				return;
			}
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsHiddenFromPlayer = this._widget_4.IsHidden;
				return;
			}
		}

		// Token: 0x06000D4D RID: 3405 RVA: 0x00065265 File Offset: 0x00063465
		private void PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D4E RID: 3406 RVA: 0x0006526E File Offset: 0x0006346E
		private void boolPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D4F RID: 3407 RVA: 0x00065277 File Offset: 0x00063477
		private void floatPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D50 RID: 3408 RVA: 0x00065280 File Offset: 0x00063480
		private void Vec2PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D51 RID: 3409 RVA: 0x00065289 File Offset: 0x00063489
		private void Vector2PropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D52 RID: 3410 RVA: 0x00065292 File Offset: 0x00063492
		private void doublePropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D53 RID: 3411 RVA: 0x0006529B File Offset: 0x0006349B
		private void intPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D54 RID: 3412 RVA: 0x000652A4 File Offset: 0x000634A4
		private void uintPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D55 RID: 3413 RVA: 0x000652AD File Offset: 0x000634AD
		private void ColorPropertyChangedListenerOf_widget_5(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_5(propertyName);
		}

		// Token: 0x06000D56 RID: 3414 RVA: 0x000652B6 File Offset: 0x000634B6
		private void HandleWidgetPropertyChangeOf_widget_5(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsHiddenFromPlayer = this._widget_5.IsVisible;
				return;
			}
		}

		// Token: 0x06000D57 RID: 3415 RVA: 0x000652DC File Offset: 0x000634DC
		private void PropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D58 RID: 3416 RVA: 0x000652E5 File Offset: 0x000634E5
		private void boolPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D59 RID: 3417 RVA: 0x000652EE File Offset: 0x000634EE
		private void floatPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D5A RID: 3418 RVA: 0x000652F7 File Offset: 0x000634F7
		private void Vec2PropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D5B RID: 3419 RVA: 0x00065300 File Offset: 0x00063500
		private void Vector2PropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D5C RID: 3420 RVA: 0x00065309 File Offset: 0x00063509
		private void doublePropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D5D RID: 3421 RVA: 0x00065312 File Offset: 0x00063512
		private void intPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D5E RID: 3422 RVA: 0x0006531B File Offset: 0x0006351B
		private void uintPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D5F RID: 3423 RVA: 0x00065324 File Offset: 0x00063524
		private void ColorPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
		}

		// Token: 0x06000D60 RID: 3424 RVA: 0x0006532D File Offset: 0x0006352D
		private void HandleWidgetPropertyChangeOf_widget_6_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsBronzeTier = this._widget_6_0.IsVisible;
				return;
			}
		}

		// Token: 0x06000D61 RID: 3425 RVA: 0x00065353 File Offset: 0x00063553
		private void PropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D62 RID: 3426 RVA: 0x0006535C File Offset: 0x0006355C
		private void boolPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D63 RID: 3427 RVA: 0x00065365 File Offset: 0x00063565
		private void floatPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D64 RID: 3428 RVA: 0x0006536E File Offset: 0x0006356E
		private void Vec2PropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D65 RID: 3429 RVA: 0x00065377 File Offset: 0x00063577
		private void Vector2PropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D66 RID: 3430 RVA: 0x00065380 File Offset: 0x00063580
		private void doublePropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D67 RID: 3431 RVA: 0x00065389 File Offset: 0x00063589
		private void intPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D68 RID: 3432 RVA: 0x00065392 File Offset: 0x00063592
		private void uintPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D69 RID: 3433 RVA: 0x0006539B File Offset: 0x0006359B
		private void ColorPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
		}

		// Token: 0x06000D6A RID: 3434 RVA: 0x000653A4 File Offset: 0x000635A4
		private void HandleWidgetPropertyChangeOf_widget_6_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsSilverTier = this._widget_6_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000D6B RID: 3435 RVA: 0x000653CA File Offset: 0x000635CA
		private void PropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D6C RID: 3436 RVA: 0x000653D3 File Offset: 0x000635D3
		private void boolPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D6D RID: 3437 RVA: 0x000653DC File Offset: 0x000635DC
		private void floatPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D6E RID: 3438 RVA: 0x000653E5 File Offset: 0x000635E5
		private void Vec2PropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D6F RID: 3439 RVA: 0x000653EE File Offset: 0x000635EE
		private void Vector2PropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D70 RID: 3440 RVA: 0x000653F7 File Offset: 0x000635F7
		private void doublePropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D71 RID: 3441 RVA: 0x00065400 File Offset: 0x00063600
		private void intPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D72 RID: 3442 RVA: 0x00065409 File Offset: 0x00063609
		private void uintPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D73 RID: 3443 RVA: 0x00065412 File Offset: 0x00063612
		private void ColorPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
		}

		// Token: 0x06000D74 RID: 3444 RVA: 0x0006541B File Offset: 0x0006361B
		private void HandleWidgetPropertyChangeOf_widget_6_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsGoldTier = this._widget_6_2.IsVisible;
				return;
			}
		}

		// Token: 0x06000D75 RID: 3445 RVA: 0x00065441 File Offset: 0x00063641
		private void PropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D76 RID: 3446 RVA: 0x0006544A File Offset: 0x0006364A
		private void boolPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D77 RID: 3447 RVA: 0x00065453 File Offset: 0x00063653
		private void floatPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D78 RID: 3448 RVA: 0x0006545C File Offset: 0x0006365C
		private void Vec2PropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D79 RID: 3449 RVA: 0x00065465 File Offset: 0x00063665
		private void Vector2PropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D7A RID: 3450 RVA: 0x0006546E File Offset: 0x0006366E
		private void doublePropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D7B RID: 3451 RVA: 0x00065477 File Offset: 0x00063677
		private void intPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D7C RID: 3452 RVA: 0x00065480 File Offset: 0x00063680
		private void uintPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D7D RID: 3453 RVA: 0x00065489 File Offset: 0x00063689
		private void ColorPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
		}

		// Token: 0x06000D7E RID: 3454 RVA: 0x00065492 File Offset: 0x00063692
		private void HandleWidgetPropertyChangeOf_widget_6_3(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsDiamondTier = this._widget_6_3.IsVisible;
				return;
			}
		}

		// Token: 0x06000D7F RID: 3455 RVA: 0x000654B8 File Offset: 0x000636B8
		private void PropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D80 RID: 3456 RVA: 0x000654C1 File Offset: 0x000636C1
		private void boolPropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D81 RID: 3457 RVA: 0x000654CA File Offset: 0x000636CA
		private void floatPropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D82 RID: 3458 RVA: 0x000654D3 File Offset: 0x000636D3
		private void Vec2PropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D83 RID: 3459 RVA: 0x000654DC File Offset: 0x000636DC
		private void Vector2PropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D84 RID: 3460 RVA: 0x000654E5 File Offset: 0x000636E5
		private void doublePropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D85 RID: 3461 RVA: 0x000654EE File Offset: 0x000636EE
		private void intPropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D86 RID: 3462 RVA: 0x000654F7 File Offset: 0x000636F7
		private void uintPropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D87 RID: 3463 RVA: 0x00065500 File Offset: 0x00063700
		private void ColorPropertyChangedListenerOf_widget_7_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_0(propertyName);
		}

		// Token: 0x06000D88 RID: 3464 RVA: 0x00065509 File Offset: 0x00063709
		private void HandleWidgetPropertyChangeOf_widget_7_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsBronzeTier = this._widget_7_0.IsVisible;
				return;
			}
		}

		// Token: 0x06000D89 RID: 3465 RVA: 0x0006552F File Offset: 0x0006372F
		private void PropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D8A RID: 3466 RVA: 0x00065538 File Offset: 0x00063738
		private void boolPropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D8B RID: 3467 RVA: 0x00065541 File Offset: 0x00063741
		private void floatPropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D8C RID: 3468 RVA: 0x0006554A File Offset: 0x0006374A
		private void Vec2PropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D8D RID: 3469 RVA: 0x00065553 File Offset: 0x00063753
		private void Vector2PropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D8E RID: 3470 RVA: 0x0006555C File Offset: 0x0006375C
		private void doublePropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D8F RID: 3471 RVA: 0x00065565 File Offset: 0x00063765
		private void intPropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D90 RID: 3472 RVA: 0x0006556E File Offset: 0x0006376E
		private void uintPropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D91 RID: 3473 RVA: 0x00065577 File Offset: 0x00063777
		private void ColorPropertyChangedListenerOf_widget_7_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_1(propertyName);
		}

		// Token: 0x06000D92 RID: 3474 RVA: 0x00065580 File Offset: 0x00063780
		private void HandleWidgetPropertyChangeOf_widget_7_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsSilverTier = this._widget_7_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000D93 RID: 3475 RVA: 0x000655A6 File Offset: 0x000637A6
		private void PropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D94 RID: 3476 RVA: 0x000655AF File Offset: 0x000637AF
		private void boolPropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D95 RID: 3477 RVA: 0x000655B8 File Offset: 0x000637B8
		private void floatPropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D96 RID: 3478 RVA: 0x000655C1 File Offset: 0x000637C1
		private void Vec2PropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D97 RID: 3479 RVA: 0x000655CA File Offset: 0x000637CA
		private void Vector2PropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D98 RID: 3480 RVA: 0x000655D3 File Offset: 0x000637D3
		private void doublePropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D99 RID: 3481 RVA: 0x000655DC File Offset: 0x000637DC
		private void intPropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D9A RID: 3482 RVA: 0x000655E5 File Offset: 0x000637E5
		private void uintPropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D9B RID: 3483 RVA: 0x000655EE File Offset: 0x000637EE
		private void ColorPropertyChangedListenerOf_widget_7_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_2(propertyName);
		}

		// Token: 0x06000D9C RID: 3484 RVA: 0x000655F7 File Offset: 0x000637F7
		private void HandleWidgetPropertyChangeOf_widget_7_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsGoldTier = this._widget_7_2.IsVisible;
				return;
			}
		}

		// Token: 0x06000D9D RID: 3485 RVA: 0x0006561D File Offset: 0x0006381D
		private void PropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000D9E RID: 3486 RVA: 0x00065626 File Offset: 0x00063826
		private void boolPropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000D9F RID: 3487 RVA: 0x0006562F File Offset: 0x0006382F
		private void floatPropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA0 RID: 3488 RVA: 0x00065638 File Offset: 0x00063838
		private void Vec2PropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA1 RID: 3489 RVA: 0x00065641 File Offset: 0x00063841
		private void Vector2PropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA2 RID: 3490 RVA: 0x0006564A File Offset: 0x0006384A
		private void doublePropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA3 RID: 3491 RVA: 0x00065653 File Offset: 0x00063853
		private void intPropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA4 RID: 3492 RVA: 0x0006565C File Offset: 0x0006385C
		private void uintPropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA5 RID: 3493 RVA: 0x00065665 File Offset: 0x00063865
		private void ColorPropertyChangedListenerOf_widget_7_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_7_3(propertyName);
		}

		// Token: 0x06000DA6 RID: 3494 RVA: 0x0006566E File Offset: 0x0006386E
		private void HandleWidgetPropertyChangeOf_widget_7_3(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsDiamondTier = this._widget_7_3.IsVisible;
				return;
			}
		}

		// Token: 0x06000DA7 RID: 3495 RVA: 0x00065694 File Offset: 0x00063894
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DA8 RID: 3496 RVA: 0x000656A2 File Offset: 0x000638A2
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DA9 RID: 3497 RVA: 0x000656B1 File Offset: 0x000638B1
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DAA RID: 3498 RVA: 0x000656C0 File Offset: 0x000638C0
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DAB RID: 3499 RVA: 0x000656CF File Offset: 0x000638CF
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DAC RID: 3500 RVA: 0x000656DE File Offset: 0x000638DE
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DAD RID: 3501 RVA: 0x000656ED File Offset: 0x000638ED
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DAE RID: 3502 RVA: 0x000656FC File Offset: 0x000638FC
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DAF RID: 3503 RVA: 0x0006570B File Offset: 0x0006390B
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000DB0 RID: 3504 RVA: 0x0006571C File Offset: 0x0006391C
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "IsBronzeTier")
			{
				this._widget_0.IsVisible = this._datasource_Root.IsBronzeTier;
				this._widget_6_0.IsVisible = this._datasource_Root.IsBronzeTier;
				this._widget_7_0.IsVisible = this._datasource_Root.IsBronzeTier;
				return;
			}
			if (propertyName == "IsSilverTier")
			{
				this._widget_1.IsVisible = this._datasource_Root.IsSilverTier;
				this._widget_6_1.IsVisible = this._datasource_Root.IsSilverTier;
				this._widget_7_1.IsVisible = this._datasource_Root.IsSilverTier;
				return;
			}
			if (propertyName == "IsGoldTier")
			{
				this._widget_2.IsVisible = this._datasource_Root.IsGoldTier;
				this._widget_6_2.IsVisible = this._datasource_Root.IsGoldTier;
				this._widget_7_2.IsVisible = this._datasource_Root.IsGoldTier;
				return;
			}
			if (propertyName == "IsDiamondTier")
			{
				this._widget_3.IsVisible = this._datasource_Root.IsDiamondTier;
				this._widget_6_3.IsVisible = this._datasource_Root.IsDiamondTier;
				this._widget_7_3.IsVisible = this._datasource_Root.IsDiamondTier;
				return;
			}
			if (propertyName == "Identifier")
			{
				this._widget_4.Identifier = this._datasource_Root.Identifier;
				return;
			}
			if (propertyName == "IsHiddenFromPlayer")
			{
				this._widget_4.IsHidden = this._datasource_Root.IsHiddenFromPlayer;
				this._widget_5.IsVisible = this._datasource_Root.IsHiddenFromPlayer;
				return;
			}
		}

		// Token: 0x06000DB1 RID: 3505 RVA: 0x000658C8 File Offset: 0x00063AC8
		private void RefreshDataSource_datasource_Root(ShipUpgradePieceBaseVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_3;
				this._widget_4.PropertyChanged -= this.PropertyChangedListenerOf_widget_4;
				this._widget_4.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_4;
				this._widget_4.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_4;
				this._widget_4.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_4;
				this._widget_4.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_4;
				this._widget_4.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_4;
				this._widget_4.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_4;
				this._widget_4.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_4;
				this._widget_4.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_4;
				this._widget_5.PropertyChanged -= this.PropertyChangedListenerOf_widget_5;
				this._widget_5.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_5;
				this._widget_5.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_5;
				this._widget_5.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_5;
				this._widget_5.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_5;
				this._widget_5.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_5;
				this._widget_5.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_5;
				this._widget_5.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_5;
				this._widget_5.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_5;
				this._widget_6_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_0;
				this._widget_6_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_1;
				this._widget_6_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_2;
				this._widget_6_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_6_3;
				this._widget_7_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_0;
				this._widget_7_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_1;
				this._widget_7_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_2;
				this._widget_7_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_7_3;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_0.IsVisible = this._datasource_Root.IsBronzeTier;
				this._widget_0.PropertyChanged += this.PropertyChangedListenerOf_widget_0;
				this._widget_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_0;
				this._widget_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_0;
				this._widget_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_0;
				this._widget_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_0;
				this._widget_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_0;
				this._widget_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_0;
				this._widget_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_0;
				this._widget_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_0;
				this._widget_1.IsVisible = this._datasource_Root.IsSilverTier;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_2.IsVisible = this._datasource_Root.IsGoldTier;
				this._widget_2.PropertyChanged += this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2;
				this._widget_3.IsVisible = this._datasource_Root.IsDiamondTier;
				this._widget_3.PropertyChanged += this.PropertyChangedListenerOf_widget_3;
				this._widget_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_3;
				this._widget_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_3;
				this._widget_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_3;
				this._widget_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_3;
				this._widget_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_3;
				this._widget_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_3;
				this._widget_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_3;
				this._widget_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_3;
				this._widget_4.Identifier = this._datasource_Root.Identifier;
				this._widget_4.IsHidden = this._datasource_Root.IsHiddenFromPlayer;
				this._widget_4.PropertyChanged += this.PropertyChangedListenerOf_widget_4;
				this._widget_4.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_4;
				this._widget_4.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_4;
				this._widget_4.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_4;
				this._widget_4.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_4;
				this._widget_4.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_4;
				this._widget_4.intPropertyChanged += this.intPropertyChangedListenerOf_widget_4;
				this._widget_4.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_4;
				this._widget_4.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_4;
				this._widget_5.IsVisible = this._datasource_Root.IsHiddenFromPlayer;
				this._widget_5.PropertyChanged += this.PropertyChangedListenerOf_widget_5;
				this._widget_5.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_5;
				this._widget_5.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_5;
				this._widget_5.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_5;
				this._widget_5.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_5;
				this._widget_5.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_5;
				this._widget_5.intPropertyChanged += this.intPropertyChangedListenerOf_widget_5;
				this._widget_5.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_5;
				this._widget_5.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_5;
				this._widget_6_0.IsVisible = this._datasource_Root.IsBronzeTier;
				this._widget_6_0.PropertyChanged += this.PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_6_0;
				this._widget_6_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_6_0;
				this._widget_6_1.IsVisible = this._datasource_Root.IsSilverTier;
				this._widget_6_1.PropertyChanged += this.PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_6_1;
				this._widget_6_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_6_1;
				this._widget_6_2.IsVisible = this._datasource_Root.IsGoldTier;
				this._widget_6_2.PropertyChanged += this.PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_6_2;
				this._widget_6_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_6_2;
				this._widget_6_3.IsVisible = this._datasource_Root.IsDiamondTier;
				this._widget_6_3.PropertyChanged += this.PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_6_3;
				this._widget_6_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_6_3;
				this._widget_7_0.IsVisible = this._datasource_Root.IsBronzeTier;
				this._widget_7_0.PropertyChanged += this.PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_7_0;
				this._widget_7_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_7_0;
				this._widget_7_1.IsVisible = this._datasource_Root.IsSilverTier;
				this._widget_7_1.PropertyChanged += this.PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_7_1;
				this._widget_7_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_7_1;
				this._widget_7_2.IsVisible = this._datasource_Root.IsGoldTier;
				this._widget_7_2.PropertyChanged += this.PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_7_2;
				this._widget_7_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_7_2;
				this._widget_7_3.IsVisible = this._datasource_Root.IsDiamondTier;
				this._widget_7_3.PropertyChanged += this.PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_7_3;
				this._widget_7_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_7_3;
			}
		}

		// Token: 0x04000201 RID: 513
		private Widget _widget;

		// Token: 0x04000202 RID: 514
		private BrushWidget _widget_0;

		// Token: 0x04000203 RID: 515
		private BrushWidget _widget_1;

		// Token: 0x04000204 RID: 516
		private BrushWidget _widget_2;

		// Token: 0x04000205 RID: 517
		private BrushWidget _widget_3;

		// Token: 0x04000206 RID: 518
		private PortPieceImageBrushWidget _widget_4;

		// Token: 0x04000207 RID: 519
		private Widget _widget_5;

		// Token: 0x04000208 RID: 520
		private Widget _widget_6;

		// Token: 0x04000209 RID: 521
		private BrushWidget _widget_6_0;

		// Token: 0x0400020A RID: 522
		private BrushWidget _widget_6_1;

		// Token: 0x0400020B RID: 523
		private BrushWidget _widget_6_2;

		// Token: 0x0400020C RID: 524
		private BrushWidget _widget_6_3;

		// Token: 0x0400020D RID: 525
		private Widget _widget_7;

		// Token: 0x0400020E RID: 526
		private BrushWidget _widget_7_0;

		// Token: 0x0400020F RID: 527
		private BrushWidget _widget_7_1;

		// Token: 0x04000210 RID: 528
		private BrushWidget _widget_7_2;

		// Token: 0x04000211 RID: 529
		private BrushWidget _widget_7_3;

		// Token: 0x04000212 RID: 530
		private ShipUpgradePieceBaseVM _datasource_Root;
	}
}
