using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.ClanManagement;
using TaleWorlds.Core.ViewModelCollection.ImageIdentifiers;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace SandBox.GauntletUI.AutoGenerated0;

public class ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate : ButtonWidget
{
	private ButtonWidget _widget;

	private BrushWidget _widget_0;

	private BrushWidget _widget_1;

	private Widget _widget_2;

	private ImageIdentifierWidget _widget_3;

	private HintWidget _widget_4;

	private ClanRoleMemberItemVM _datasource_Root;

	private HintViewModel _datasource_Root_Hint;

	private ClanPartyMemberItemVM _datasource_Root_Member;

	private CharacterImageIdentifierVM _datasource_Root_Member_Visual;

	public ClanScreen__TaleWorlds_CampaignSystem_ViewModelCollection_ClanManagement_ClanManagementVM_Dependency_13_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		_widget = this;
		_widget_0 = new BrushWidget(base.Context);
		_widget.AddChild(_widget_0);
		_widget_1 = new BrushWidget(base.Context);
		_widget.AddChild(_widget_1);
		_widget_2 = new Widget(base.Context);
		_widget.AddChild(_widget_2);
		_widget_3 = new ImageIdentifierWidget(base.Context);
		_widget.AddChild(_widget_3);
		_widget_4 = new HintWidget(base.Context);
		_widget.AddChild(_widget_4);
	}

	public void SetIds()
	{
	}

	public void SetAttributes()
	{
		base.DoNotPassEventsToChildren = true;
		base.WidthSizePolicy = SizePolicy.StretchToParent;
		base.HeightSizePolicy = SizePolicy.StretchToParent;
		base.MarginLeft = 5f;
		base.MarginRight = 5f;
		base.MarginTop = 5f;
		base.MarginBottom = 5f;
		base.UpdateChildrenStates = true;
		_widget_0.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_0.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_0.Brush = base.Context.GetBrush("SPClan.RoleSelectionButton.GoldFrame");
		_widget_1.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_1.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_1.Brush = base.Context.GetBrush("TownManagement.GovernorPopup.Governor.Background");
		_widget_2.WidthSizePolicy = SizePolicy.Fixed;
		_widget_2.HeightSizePolicy = SizePolicy.Fixed;
		_widget_2.SuggestedWidth = 35f;
		_widget_2.SuggestedHeight = 35f;
		_widget_2.HorizontalAlignment = HorizontalAlignment.Center;
		_widget_2.VerticalAlignment = VerticalAlignment.Center;
		_widget_2.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\none");
		_widget_3.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_3.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_4.WidthSizePolicy = SizePolicy.StretchToParent;
		_widget_4.HeightSizePolicy = SizePolicy.StretchToParent;
		_widget_4.IsDisabled = false;
	}

	public void DestroyDataSource()
	{
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget.EventFire -= EventListenerOf_widget;
		_widget_2.PropertyChanged -= PropertyChangedListenerOf_widget_2;
		_widget_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
		_widget_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
		_widget_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
		_widget_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
		_widget_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
		_widget_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
		_widget_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
		_widget_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
		if (_datasource_Root_Hint != null)
		{
			_datasource_Root_Hint.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
			_widget_4.EventFire -= EventListenerOf_widget_4;
			_datasource_Root_Hint = null;
		}
		if (_datasource_Root_Member != null)
		{
			_datasource_Root_Member.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member;
			if (_datasource_Root_Member_Visual != null)
			{
				_datasource_Root_Member_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
				_widget_3.PropertyChanged -= PropertyChangedListenerOf_widget_3;
				_widget_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
				_widget_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
				_widget_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
				_widget_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
				_widget_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
				_widget_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
				_widget_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
				_widget_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
				_datasource_Root_Member_Visual = null;
			}
			_datasource_Root_Member = null;
		}
		_datasource_Root = null;
	}

	public void SetDataSource(ClanRoleMemberItemVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
	{
		if (commandName == "Click")
		{
			_datasource_Root.ExecuteAssignHeroToRole();
		}
	}

	private void EventListenerOf_widget_4(Widget widget, string commandName, object[] args)
	{
		if (commandName == "HoverBegin")
		{
			_datasource_Root_Hint.ExecuteBeginHint();
		}
		if (commandName == "HoverEnd")
		{
			_datasource_Root_Hint.ExecuteEndHint();
		}
	}

	private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsRemoveAssigneeOption = _widget_2.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_3(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_datasource_Root_Member_Visual.AdditionalArgs = _widget_3.AdditionalArgs;
			break;
		case "ImageId":
			_datasource_Root_Member_Visual.Id = _widget_3.ImageId;
			break;
		case "TextureProviderName":
			_datasource_Root_Member_Visual.TextureProviderName = _widget_3.TextureProviderName;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "Hint":
			RefreshDataSource_datasource_Root_Hint(_datasource_Root.Hint);
			break;
		case "Member":
			RefreshDataSource_datasource_Root_Member(_datasource_Root.Member);
			break;
		case "IsRemoveAssigneeOption":
			_widget_2.IsVisible = _datasource_Root.IsRemoveAssigneeOption;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Member_Visual(string propertyName)
	{
		switch (propertyName)
		{
		case "AdditionalArgs":
			_widget_3.AdditionalArgs = _datasource_Root_Member_Visual.AdditionalArgs;
			break;
		case "Id":
			_widget_3.ImageId = _datasource_Root_Member_Visual.Id;
			break;
		case "TextureProviderName":
			_widget_3.TextureProviderName = _datasource_Root_Member_Visual.TextureProviderName;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Hint(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Hint(string propertyName)
	{
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Member(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Member(e.PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Member(string propertyName)
	{
		if (propertyName == "Visual")
		{
			RefreshDataSource_datasource_Root_Member_Visual(_datasource_Root_Member.Visual);
		}
	}

	private void RefreshDataSource_datasource_Root(ClanRoleMemberItemVM newDataSource)
	{
		if (_datasource_Root != null)
		{
			_datasource_Root.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
			_datasource_Root.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
			_widget.EventFire -= EventListenerOf_widget;
			_widget_2.PropertyChanged -= PropertyChangedListenerOf_widget_2;
			_widget_2.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			_widget_2.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			_widget_2.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			_widget_2.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			_widget_2.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			_widget_2.intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			_widget_2.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			_widget_2.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			if (_datasource_Root_Hint != null)
			{
				_datasource_Root_Hint.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
				_datasource_Root_Hint.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
				_widget_4.EventFire -= EventListenerOf_widget_4;
				_datasource_Root_Hint = null;
			}
			if (_datasource_Root_Member != null)
			{
				_datasource_Root_Member.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member;
				_datasource_Root_Member.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member;
				if (_datasource_Root_Member_Visual != null)
				{
					_datasource_Root_Member_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
					_datasource_Root_Member_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
					_widget_3.PropertyChanged -= PropertyChangedListenerOf_widget_3;
					_widget_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
					_widget_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
					_widget_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
					_widget_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
					_widget_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
					_widget_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
					_widget_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
					_widget_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
					_datasource_Root_Member_Visual = null;
				}
				_datasource_Root_Member = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		_datasource_Root.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root;
		_datasource_Root.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root;
		_widget.EventFire += EventListenerOf_widget;
		_widget_2.IsVisible = _datasource_Root.IsRemoveAssigneeOption;
		_widget_2.PropertyChanged += PropertyChangedListenerOf_widget_2;
		_widget_2.boolPropertyChanged += boolPropertyChangedListenerOf_widget_2;
		_widget_2.floatPropertyChanged += floatPropertyChangedListenerOf_widget_2;
		_widget_2.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2;
		_widget_2.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2;
		_widget_2.doublePropertyChanged += doublePropertyChangedListenerOf_widget_2;
		_widget_2.intPropertyChanged += intPropertyChangedListenerOf_widget_2;
		_widget_2.uintPropertyChanged += uintPropertyChangedListenerOf_widget_2;
		_widget_2.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2;
		_datasource_Root_Hint = _datasource_Root.Hint;
		if (_datasource_Root_Hint != null)
		{
			_datasource_Root_Hint.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
			_widget_4.EventFire += EventListenerOf_widget_4;
		}
		_datasource_Root_Member = _datasource_Root.Member;
		if (_datasource_Root_Member != null)
		{
			_datasource_Root_Member.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member_Visual = _datasource_Root_Member.Visual;
			if (_datasource_Root_Member_Visual != null)
			{
				_datasource_Root_Member_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
				_widget_3.AdditionalArgs = _datasource_Root_Member_Visual.AdditionalArgs;
				_widget_3.ImageId = _datasource_Root_Member_Visual.Id;
				_widget_3.TextureProviderName = _datasource_Root_Member_Visual.TextureProviderName;
				_widget_3.PropertyChanged += PropertyChangedListenerOf_widget_3;
				_widget_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_3;
				_widget_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_3;
				_widget_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_3;
				_widget_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_3;
				_widget_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_3;
				_widget_3.intPropertyChanged += intPropertyChangedListenerOf_widget_3;
				_widget_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_3;
				_widget_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_3;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Member_Visual(CharacterImageIdentifierVM newDataSource)
	{
		if (_datasource_Root_Member_Visual != null)
		{
			_datasource_Root_Member_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
			_widget_3.PropertyChanged -= PropertyChangedListenerOf_widget_3;
			_widget_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
			_widget_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
			_widget_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
			_widget_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
			_widget_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
			_widget_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
			_widget_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
			_widget_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
			_datasource_Root_Member_Visual = null;
		}
		_datasource_Root_Member_Visual = newDataSource;
		_datasource_Root_Member_Visual = _datasource_Root_Member.Visual;
		if (_datasource_Root_Member_Visual != null)
		{
			_datasource_Root_Member_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
			_datasource_Root_Member_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
			_widget_3.AdditionalArgs = _datasource_Root_Member_Visual.AdditionalArgs;
			_widget_3.ImageId = _datasource_Root_Member_Visual.Id;
			_widget_3.TextureProviderName = _datasource_Root_Member_Visual.TextureProviderName;
			_widget_3.PropertyChanged += PropertyChangedListenerOf_widget_3;
			_widget_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_3;
			_widget_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_3;
			_widget_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_3;
			_widget_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_3;
			_widget_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_3;
			_widget_3.intPropertyChanged += intPropertyChangedListenerOf_widget_3;
			_widget_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_3;
			_widget_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_3;
		}
	}

	private void RefreshDataSource_datasource_Root_Hint(HintViewModel newDataSource)
	{
		if (_datasource_Root_Hint != null)
		{
			_datasource_Root_Hint.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
			_widget_4.EventFire -= EventListenerOf_widget_4;
			_datasource_Root_Hint = null;
		}
		_datasource_Root_Hint = newDataSource;
		_datasource_Root_Hint = _datasource_Root.Hint;
		if (_datasource_Root_Hint != null)
		{
			_datasource_Root_Hint.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint;
			_datasource_Root_Hint.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint;
			_widget_4.EventFire += EventListenerOf_widget_4;
		}
	}

	private void RefreshDataSource_datasource_Root_Member(ClanPartyMemberItemVM newDataSource)
	{
		if (_datasource_Root_Member != null)
		{
			_datasource_Root_Member.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member;
			if (_datasource_Root_Member_Visual != null)
			{
				_datasource_Root_Member_Visual.PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithValue -= ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithBoolValue -= ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithIntValue -= ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithFloatValue -= ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithUIntValue -= ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithColorValue -= ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue -= ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithVec2Value -= ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
				_widget_3.PropertyChanged -= PropertyChangedListenerOf_widget_3;
				_widget_3.boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
				_widget_3.floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
				_widget_3.Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
				_widget_3.Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
				_widget_3.doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
				_widget_3.intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
				_widget_3.uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
				_widget_3.ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
				_datasource_Root_Member_Visual = null;
			}
			_datasource_Root_Member = null;
		}
		_datasource_Root_Member = newDataSource;
		_datasource_Root_Member = _datasource_Root.Member;
		if (_datasource_Root_Member != null)
		{
			_datasource_Root_Member.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member;
			_datasource_Root_Member_Visual = _datasource_Root_Member.Visual;
			if (_datasource_Root_Member_Visual != null)
			{
				_datasource_Root_Member_Visual.PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithValue += ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithBoolValue += ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithIntValue += ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithFloatValue += ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithUIntValue += ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithColorValue += ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithDoubleValue += ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Member_Visual;
				_datasource_Root_Member_Visual.PropertyChangedWithVec2Value += ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Member_Visual;
				_widget_3.AdditionalArgs = _datasource_Root_Member_Visual.AdditionalArgs;
				_widget_3.ImageId = _datasource_Root_Member_Visual.Id;
				_widget_3.TextureProviderName = _datasource_Root_Member_Visual.TextureProviderName;
				_widget_3.PropertyChanged += PropertyChangedListenerOf_widget_3;
				_widget_3.boolPropertyChanged += boolPropertyChangedListenerOf_widget_3;
				_widget_3.floatPropertyChanged += floatPropertyChangedListenerOf_widget_3;
				_widget_3.Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_3;
				_widget_3.Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_3;
				_widget_3.doublePropertyChanged += doublePropertyChangedListenerOf_widget_3;
				_widget_3.intPropertyChanged += intPropertyChangedListenerOf_widget_3;
				_widget_3.uintPropertyChanged += uintPropertyChangedListenerOf_widget_3;
				_widget_3.ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_3;
			}
		}
	}
}
