using System;
using System.ComponentModel;
using System.Numerics;
using TaleWorlds.CampaignSystem.ViewModelCollection.Input;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;

namespace NavalDLC.GauntletUI.AutoGenerated
{
	// Token: 0x0200000A RID: 10
	public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_8_ItemTemplate : InputKeyVisualWidget
	{
		// Token: 0x060003A6 RID: 934 RVA: 0x0002183D File Offset: 0x0001FA3D
		public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_8_ItemTemplate(UIContext context)
			: base(context)
		{
		}

		// Token: 0x060003A7 RID: 935 RVA: 0x00021848 File Offset: 0x0001FA48
		private VisualDefinition CreateVisualDefinitionCameraControls()
		{
			VisualDefinition visualDefinition = new VisualDefinition("CameraControls", 0.45f, 0f, 2, 4);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				MarginBottom = 60f
			});
			visualDefinition.AddVisualState(new VisualState("Extended")
			{
				MarginBottom = 96f
			});
			return visualDefinition;
		}

		// Token: 0x060003A8 RID: 936 RVA: 0x000218A8 File Offset: 0x0001FAA8
		private VisualDefinition CreateVisualDefinitionShip_Slot()
		{
			VisualDefinition visualDefinition = new VisualDefinition("Ship.Slot", 0.15f, 0f, 3, 0);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				SuggestedWidth = 70f,
				SuggestedHeight = 70f
			});
			visualDefinition.AddVisualState(new VisualState("Hovered")
			{
				SuggestedWidth = 71.75f,
				SuggestedHeight = 71.75f
			});
			visualDefinition.AddVisualState(new VisualState("Pressed")
			{
				SuggestedWidth = 68.25f,
				SuggestedHeight = 68.25f
			});
			visualDefinition.AddVisualState(new VisualState("Selected")
			{
				SuggestedWidth = 73.5f,
				SuggestedHeight = 73.5f
			});
			return visualDefinition;
		}

		// Token: 0x060003A9 RID: 937 RVA: 0x0002196B File Offset: 0x0001FB6B
		public void CreateWidgets()
		{
			this._widget = this;
		}

		// Token: 0x060003AA RID: 938 RVA: 0x00021974 File Offset: 0x0001FB74
		public void SetIds()
		{
		}

		// Token: 0x060003AB RID: 939 RVA: 0x00021976 File Offset: 0x0001FB76
		public void SetAttributes()
		{
			base.WidthSizePolicy = 0;
			base.HeightSizePolicy = 0;
			base.SuggestedWidth = 50f;
			base.SuggestedHeight = 50f;
			base.MarginLeft = -10f;
			base.VerticalAlignment = 1;
		}

		// Token: 0x060003AC RID: 940 RVA: 0x000219B0 File Offset: 0x0001FBB0
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._datasource_Root = null;
			}
		}

		// Token: 0x060003AD RID: 941 RVA: 0x00021B6D File Offset: 0x0001FD6D
		public void SetDataSource(InputKeyItemVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x060003AE RID: 942 RVA: 0x00021B76 File Offset: 0x0001FD76
		private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003AF RID: 943 RVA: 0x00021B7F File Offset: 0x0001FD7F
		private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B0 RID: 944 RVA: 0x00021B88 File Offset: 0x0001FD88
		private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B1 RID: 945 RVA: 0x00021B91 File Offset: 0x0001FD91
		private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B2 RID: 946 RVA: 0x00021B9A File Offset: 0x0001FD9A
		private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B3 RID: 947 RVA: 0x00021BA3 File Offset: 0x0001FDA3
		private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B4 RID: 948 RVA: 0x00021BAC File Offset: 0x0001FDAC
		private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B5 RID: 949 RVA: 0x00021BB5 File Offset: 0x0001FDB5
		private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B6 RID: 950 RVA: 0x00021BBE File Offset: 0x0001FDBE
		private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget(propertyName);
		}

		// Token: 0x060003B7 RID: 951 RVA: 0x00021BC8 File Offset: 0x0001FDC8
		private void HandleWidgetPropertyChangeOf_widget(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._datasource_Root.KeyID = this._widget.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsVisible = this._widget.IsVisible;
				return;
			}
		}

		// Token: 0x060003B8 RID: 952 RVA: 0x00021C1D File Offset: 0x0001FE1D
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003B9 RID: 953 RVA: 0x00021C2B File Offset: 0x0001FE2B
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003BA RID: 954 RVA: 0x00021C3A File Offset: 0x0001FE3A
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003BB RID: 955 RVA: 0x00021C49 File Offset: 0x0001FE49
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003BC RID: 956 RVA: 0x00021C58 File Offset: 0x0001FE58
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003BD RID: 957 RVA: 0x00021C67 File Offset: 0x0001FE67
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003BE RID: 958 RVA: 0x00021C76 File Offset: 0x0001FE76
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003BF RID: 959 RVA: 0x00021C85 File Offset: 0x0001FE85
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003C0 RID: 960 RVA: 0x00021C94 File Offset: 0x0001FE94
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x060003C1 RID: 961 RVA: 0x00021CA4 File Offset: 0x0001FEA4
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "KeyID")
			{
				this._widget.KeyID = this._datasource_Root.KeyID;
				return;
			}
			if (propertyName == "IsVisible")
			{
				this._widget.IsVisible = this._datasource_Root.IsVisible;
				return;
			}
		}

		// Token: 0x060003C2 RID: 962 RVA: 0x00021CFC File Offset: 0x0001FEFC
		private void RefreshDataSource_datasource_Root(InputKeyItemVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.PropertyChanged -= this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged -= this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.KeyID = this._datasource_Root.KeyID;
				this._widget.IsVisible = this._datasource_Root.IsVisible;
				this._widget.PropertyChanged += this.PropertyChangedListenerOf_widget;
				this._widget.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget;
				this._widget.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget;
				this._widget.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget;
				this._widget.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget;
				this._widget.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget;
				this._widget.intPropertyChanged += this.intPropertyChangedListenerOf_widget;
				this._widget.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget;
				this._widget.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget;
			}
		}

		// Token: 0x040000AE RID: 174
		private InputKeyVisualWidget _widget;

		// Token: 0x040000AF RID: 175
		private InputKeyItemVM _datasource_Root;
	}
}
