using System;
using System.ComponentModel;
using System.Numerics;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace NavalDLC.GauntletUI.AutoGenerated
{
	// Token: 0x0200001F RID: 31
	public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_29_ItemTemplate : Widget
	{
		// Token: 0x06000E15 RID: 3605 RVA: 0x00069C80 File Offset: 0x00067E80
		public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_29_ItemTemplate(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06000E16 RID: 3606 RVA: 0x00069C8C File Offset: 0x00067E8C
		private VisualDefinition CreateVisualDefinitionShip_Image()
		{
			VisualDefinition visualDefinition = new VisualDefinition("Ship.Image", 0.15f, 0f, 3, 0);
			visualDefinition.AddVisualState(new VisualState("Default")
			{
				SuggestedWidth = 212.1f
			});
			visualDefinition.AddVisualState(new VisualState("Hovered")
			{
				SuggestedWidth = 222.2f
			});
			visualDefinition.AddVisualState(new VisualState("Pressed")
			{
				SuggestedWidth = 202f
			});
			visualDefinition.AddVisualState(new VisualState("Selected")
			{
				SuggestedWidth = 232.3f
			});
			return visualDefinition;
		}

		// Token: 0x06000E17 RID: 3607 RVA: 0x00069D24 File Offset: 0x00067F24
		public void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new Widget(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new Widget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_1 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
			this._widget_1_1_0 = new Widget(base.Context);
			this._widget_1_1.AddChild(this._widget_1_1_0);
			this._widget_1_1_1 = new Widget(base.Context);
			this._widget_1_1.AddChild(this._widget_1_1_1);
			this._widget_1_1_2 = new Widget(base.Context);
			this._widget_1_1.AddChild(this._widget_1_1_2);
			this._widget_1_1_3 = new Widget(base.Context);
			this._widget_1_1.AddChild(this._widget_1_1_3);
			this._widget_2 = new Widget(base.Context);
			this._widget.AddChild(this._widget_2);
		}

		// Token: 0x06000E18 RID: 3608 RVA: 0x00069E6A File Offset: 0x0006806A
		public void SetIds()
		{
		}

		// Token: 0x06000E19 RID: 3609 RVA: 0x00069E6C File Offset: 0x0006806C
		public void SetAttributes()
		{
			base.WidthSizePolicy = 0;
			base.HeightSizePolicy = 0;
			base.SuggestedWidth = 9f;
			base.SuggestedHeight = 9f;
			base.MarginBottom = 3f;
			this._widget_0.WidthSizePolicy = 1;
			this._widget_0.HeightSizePolicy = 1;
			this._widget_0.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon");
			this._widget_0.Color = new Color(0f, 0f, 0f, 0.4f);
			this._widget_1.WidthSizePolicy = 1;
			this._widget_1.HeightSizePolicy = 1;
			this._widget_1_0.WidthSizePolicy = 1;
			this._widget_1_0.HeightSizePolicy = 1;
			this._widget_1_0.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_shadow");
			this._widget_1_0.ExtendLeft = 1f;
			this._widget_1_0.ExtendRight = 1f;
			this._widget_1_0.ExtendTop = 1f;
			this._widget_1_0.ExtendBottom = 1f;
			this._widget_1_0.Color = new Color(0f, 0f, 0f, 1f);
			this._widget_1_1.WidthSizePolicy = 1;
			this._widget_1_1.HeightSizePolicy = 1;
			this._widget_1_1_0.WidthSizePolicy = 1;
			this._widget_1_1_0.HeightSizePolicy = 1;
			this._widget_1_1_0.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_bronze");
			this._widget_1_1_1.WidthSizePolicy = 1;
			this._widget_1_1_1.HeightSizePolicy = 1;
			this._widget_1_1_1.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_silver");
			this._widget_1_1_2.WidthSizePolicy = 1;
			this._widget_1_1_2.HeightSizePolicy = 1;
			this._widget_1_1_2.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_gold");
			this._widget_1_1_3.WidthSizePolicy = 1;
			this._widget_1_1_3.HeightSizePolicy = 1;
			this._widget_1_1_3.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_diamond");
			this._widget_2.WidthSizePolicy = 1;
			this._widget_2.HeightSizePolicy = 1;
			this._widget_2.Sprite = base.Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_glow");
			this._widget_2.ExtendLeft = 2f;
			this._widget_2.ExtendRight = 2f;
			this._widget_2.ExtendTop = 2f;
			this._widget_2.ExtendBottom = 2f;
			this._widget_2.Color = new Color(0.9960785f, 0.7568628f, 0.3411765f, 1f);
		}

		// Token: 0x06000E1A RID: 3610 RVA: 0x0006A14C File Offset: 0x0006834C
		public void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				if (this._datasource_Root_SelectedPiece != null)
				{
					this._datasource_Root_SelectedPiece.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
					this._datasource_Root_SelectedPiece.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
					this._widget_1_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_3;
					this._datasource_Root_SelectedPiece = null;
				}
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000E1B RID: 3611 RVA: 0x0006A8C4 File Offset: 0x00068AC4
		public void SetDataSource(ShipUpgradeSlotBaseVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000E1C RID: 3612 RVA: 0x0006A8CD File Offset: 0x00068ACD
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E1D RID: 3613 RVA: 0x0006A8D6 File Offset: 0x00068AD6
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E1E RID: 3614 RVA: 0x0006A8DF File Offset: 0x00068ADF
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E1F RID: 3615 RVA: 0x0006A8E8 File Offset: 0x00068AE8
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E20 RID: 3616 RVA: 0x0006A8F1 File Offset: 0x00068AF1
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E21 RID: 3617 RVA: 0x0006A8FA File Offset: 0x00068AFA
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E22 RID: 3618 RVA: 0x0006A903 File Offset: 0x00068B03
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E23 RID: 3619 RVA: 0x0006A90C File Offset: 0x00068B0C
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E24 RID: 3620 RVA: 0x0006A915 File Offset: 0x00068B15
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000E25 RID: 3621 RVA: 0x0006A91E File Offset: 0x00068B1E
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.HasSelectedPiece = this._widget_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000E26 RID: 3622 RVA: 0x0006A944 File Offset: 0x00068B44
		private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E27 RID: 3623 RVA: 0x0006A94D File Offset: 0x00068B4D
		private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E28 RID: 3624 RVA: 0x0006A956 File Offset: 0x00068B56
		private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E29 RID: 3625 RVA: 0x0006A95F File Offset: 0x00068B5F
		private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E2A RID: 3626 RVA: 0x0006A968 File Offset: 0x00068B68
		private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E2B RID: 3627 RVA: 0x0006A971 File Offset: 0x00068B71
		private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E2C RID: 3628 RVA: 0x0006A97A File Offset: 0x00068B7A
		private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E2D RID: 3629 RVA: 0x0006A983 File Offset: 0x00068B83
		private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E2E RID: 3630 RVA: 0x0006A98C File Offset: 0x00068B8C
		private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
		}

		// Token: 0x06000E2F RID: 3631 RVA: 0x0006A995 File Offset: 0x00068B95
		private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsChanged = this._widget_1_0.IsHidden;
				return;
			}
		}

		// Token: 0x06000E30 RID: 3632 RVA: 0x0006A9BB File Offset: 0x00068BBB
		private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E31 RID: 3633 RVA: 0x0006A9C4 File Offset: 0x00068BC4
		private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E32 RID: 3634 RVA: 0x0006A9CD File Offset: 0x00068BCD
		private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E33 RID: 3635 RVA: 0x0006A9D6 File Offset: 0x00068BD6
		private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E34 RID: 3636 RVA: 0x0006A9DF File Offset: 0x00068BDF
		private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E35 RID: 3637 RVA: 0x0006A9E8 File Offset: 0x00068BE8
		private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E36 RID: 3638 RVA: 0x0006A9F1 File Offset: 0x00068BF1
		private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E37 RID: 3639 RVA: 0x0006A9FA File Offset: 0x00068BFA
		private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E38 RID: 3640 RVA: 0x0006AA03 File Offset: 0x00068C03
		private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_2(propertyName);
		}

		// Token: 0x06000E39 RID: 3641 RVA: 0x0006AA0C File Offset: 0x00068C0C
		private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsChanged = this._widget_2.IsVisible;
				return;
			}
		}

		// Token: 0x06000E3A RID: 3642 RVA: 0x0006AA32 File Offset: 0x00068C32
		private void PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E3B RID: 3643 RVA: 0x0006AA3B File Offset: 0x00068C3B
		private void boolPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E3C RID: 3644 RVA: 0x0006AA44 File Offset: 0x00068C44
		private void floatPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E3D RID: 3645 RVA: 0x0006AA4D File Offset: 0x00068C4D
		private void Vec2PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E3E RID: 3646 RVA: 0x0006AA56 File Offset: 0x00068C56
		private void Vector2PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E3F RID: 3647 RVA: 0x0006AA5F File Offset: 0x00068C5F
		private void doublePropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E40 RID: 3648 RVA: 0x0006AA68 File Offset: 0x00068C68
		private void intPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E41 RID: 3649 RVA: 0x0006AA71 File Offset: 0x00068C71
		private void uintPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E42 RID: 3650 RVA: 0x0006AA7A File Offset: 0x00068C7A
		private void ColorPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
		}

		// Token: 0x06000E43 RID: 3651 RVA: 0x0006AA83 File Offset: 0x00068C83
		private void HandleWidgetPropertyChangeOf_widget_1_1_0(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_SelectedPiece.IsBronzeTier = this._widget_1_1_0.IsVisible;
				return;
			}
		}

		// Token: 0x06000E44 RID: 3652 RVA: 0x0006AAA9 File Offset: 0x00068CA9
		private void PropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E45 RID: 3653 RVA: 0x0006AAB2 File Offset: 0x00068CB2
		private void boolPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E46 RID: 3654 RVA: 0x0006AABB File Offset: 0x00068CBB
		private void floatPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E47 RID: 3655 RVA: 0x0006AAC4 File Offset: 0x00068CC4
		private void Vec2PropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E48 RID: 3656 RVA: 0x0006AACD File Offset: 0x00068CCD
		private void Vector2PropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E49 RID: 3657 RVA: 0x0006AAD6 File Offset: 0x00068CD6
		private void doublePropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E4A RID: 3658 RVA: 0x0006AADF File Offset: 0x00068CDF
		private void intPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E4B RID: 3659 RVA: 0x0006AAE8 File Offset: 0x00068CE8
		private void uintPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E4C RID: 3660 RVA: 0x0006AAF1 File Offset: 0x00068CF1
		private void ColorPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
		}

		// Token: 0x06000E4D RID: 3661 RVA: 0x0006AAFA File Offset: 0x00068CFA
		private void HandleWidgetPropertyChangeOf_widget_1_1_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_SelectedPiece.IsSilverTier = this._widget_1_1_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000E4E RID: 3662 RVA: 0x0006AB20 File Offset: 0x00068D20
		private void PropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E4F RID: 3663 RVA: 0x0006AB29 File Offset: 0x00068D29
		private void boolPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E50 RID: 3664 RVA: 0x0006AB32 File Offset: 0x00068D32
		private void floatPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E51 RID: 3665 RVA: 0x0006AB3B File Offset: 0x00068D3B
		private void Vec2PropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E52 RID: 3666 RVA: 0x0006AB44 File Offset: 0x00068D44
		private void Vector2PropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E53 RID: 3667 RVA: 0x0006AB4D File Offset: 0x00068D4D
		private void doublePropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E54 RID: 3668 RVA: 0x0006AB56 File Offset: 0x00068D56
		private void intPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E55 RID: 3669 RVA: 0x0006AB5F File Offset: 0x00068D5F
		private void uintPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E56 RID: 3670 RVA: 0x0006AB68 File Offset: 0x00068D68
		private void ColorPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
		}

		// Token: 0x06000E57 RID: 3671 RVA: 0x0006AB71 File Offset: 0x00068D71
		private void HandleWidgetPropertyChangeOf_widget_1_1_2(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_SelectedPiece.IsGoldTier = this._widget_1_1_2.IsVisible;
				return;
			}
		}

		// Token: 0x06000E58 RID: 3672 RVA: 0x0006AB97 File Offset: 0x00068D97
		private void PropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E59 RID: 3673 RVA: 0x0006ABA0 File Offset: 0x00068DA0
		private void boolPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E5A RID: 3674 RVA: 0x0006ABA9 File Offset: 0x00068DA9
		private void floatPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E5B RID: 3675 RVA: 0x0006ABB2 File Offset: 0x00068DB2
		private void Vec2PropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E5C RID: 3676 RVA: 0x0006ABBB File Offset: 0x00068DBB
		private void Vector2PropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E5D RID: 3677 RVA: 0x0006ABC4 File Offset: 0x00068DC4
		private void doublePropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E5E RID: 3678 RVA: 0x0006ABCD File Offset: 0x00068DCD
		private void intPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E5F RID: 3679 RVA: 0x0006ABD6 File Offset: 0x00068DD6
		private void uintPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E60 RID: 3680 RVA: 0x0006ABDF File Offset: 0x00068DDF
		private void ColorPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
		}

		// Token: 0x06000E61 RID: 3681 RVA: 0x0006ABE8 File Offset: 0x00068DE8
		private void HandleWidgetPropertyChangeOf_widget_1_1_3(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root_SelectedPiece.IsDiamondTier = this._widget_1_1_3.IsVisible;
				return;
			}
		}

		// Token: 0x06000E62 RID: 3682 RVA: 0x0006AC0E File Offset: 0x00068E0E
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E63 RID: 3683 RVA: 0x0006AC1C File Offset: 0x00068E1C
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E64 RID: 3684 RVA: 0x0006AC2B File Offset: 0x00068E2B
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E65 RID: 3685 RVA: 0x0006AC3A File Offset: 0x00068E3A
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E66 RID: 3686 RVA: 0x0006AC49 File Offset: 0x00068E49
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E67 RID: 3687 RVA: 0x0006AC58 File Offset: 0x00068E58
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E68 RID: 3688 RVA: 0x0006AC67 File Offset: 0x00068E67
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E69 RID: 3689 RVA: 0x0006AC76 File Offset: 0x00068E76
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E6A RID: 3690 RVA: 0x0006AC85 File Offset: 0x00068E85
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000E6B RID: 3691 RVA: 0x0006AC94 File Offset: 0x00068E94
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "SelectedPiece")
			{
				this.RefreshDataSource_datasource_Root_SelectedPiece(this._datasource_Root.SelectedPiece);
				return;
			}
			if (propertyName == "HasSelectedPiece")
			{
				this._widget_1.IsVisible = this._datasource_Root.HasSelectedPiece;
				return;
			}
			if (propertyName == "IsChanged")
			{
				this._widget_1_0.IsHidden = this._datasource_Root.IsChanged;
				this._widget_2.IsVisible = this._datasource_Root.IsChanged;
				return;
			}
		}

		// Token: 0x06000E6C RID: 3692 RVA: 0x0006AD1E File Offset: 0x00068F1E
		private void ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E6D RID: 3693 RVA: 0x0006AD2C File Offset: 0x00068F2C
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E6E RID: 3694 RVA: 0x0006AD3B File Offset: 0x00068F3B
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E6F RID: 3695 RVA: 0x0006AD4A File Offset: 0x00068F4A
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E70 RID: 3696 RVA: 0x0006AD59 File Offset: 0x00068F59
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E71 RID: 3697 RVA: 0x0006AD68 File Offset: 0x00068F68
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E72 RID: 3698 RVA: 0x0006AD77 File Offset: 0x00068F77
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E73 RID: 3699 RVA: 0x0006AD86 File Offset: 0x00068F86
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E74 RID: 3700 RVA: 0x0006AD95 File Offset: 0x00068F95
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
		}

		// Token: 0x06000E75 RID: 3701 RVA: 0x0006ADA4 File Offset: 0x00068FA4
		private void HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(string propertyName)
		{
			if (propertyName == "IsBronzeTier")
			{
				this._widget_1_1_0.IsVisible = this._datasource_Root_SelectedPiece.IsBronzeTier;
				return;
			}
			if (propertyName == "IsSilverTier")
			{
				this._widget_1_1_1.IsVisible = this._datasource_Root_SelectedPiece.IsSilverTier;
				return;
			}
			if (propertyName == "IsGoldTier")
			{
				this._widget_1_1_2.IsVisible = this._datasource_Root_SelectedPiece.IsGoldTier;
				return;
			}
			if (propertyName == "IsDiamondTier")
			{
				this._widget_1_1_3.IsVisible = this._datasource_Root_SelectedPiece.IsDiamondTier;
				return;
			}
		}

		// Token: 0x06000E76 RID: 3702 RVA: 0x0006AE44 File Offset: 0x00069044
		private void RefreshDataSource_datasource_Root(ShipUpgradeSlotBaseVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_2;
				if (this._datasource_Root_SelectedPiece != null)
				{
					this._datasource_Root_SelectedPiece.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
					this._datasource_Root_SelectedPiece.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
					this._widget_1_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_3;
					this._datasource_Root_SelectedPiece = null;
				}
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget_1.IsVisible = this._datasource_Root.HasSelectedPiece;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_0.IsHidden = this._datasource_Root.IsChanged;
				this._widget_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_0;
				this._widget_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_0;
				this._widget_2.IsVisible = this._datasource_Root.IsChanged;
				this._widget_2.PropertyChanged += this.PropertyChangedListenerOf_widget_2;
				this._widget_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_2;
				this._widget_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_2;
				this._widget_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_2;
				this._widget_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_2;
				this._widget_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_2;
				this._widget_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_2;
				this._widget_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_2;
				this._widget_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_2;
				this._datasource_Root_SelectedPiece = this._datasource_Root.SelectedPiece;
				if (this._datasource_Root_SelectedPiece != null)
				{
					this._datasource_Root_SelectedPiece.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
					this._datasource_Root_SelectedPiece.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
					this._datasource_Root_SelectedPiece.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
					this._widget_1_1_0.IsVisible = this._datasource_Root_SelectedPiece.IsBronzeTier;
					this._widget_1_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_0;
					this._widget_1_1_1.IsVisible = this._datasource_Root_SelectedPiece.IsSilverTier;
					this._widget_1_1_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_1;
					this._widget_1_1_2.IsVisible = this._datasource_Root_SelectedPiece.IsGoldTier;
					this._widget_1_1_2.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_2;
					this._widget_1_1_3.IsVisible = this._datasource_Root_SelectedPiece.IsDiamondTier;
					this._widget_1_1_3.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_3;
					this._widget_1_1_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_3;
				}
			}
		}

		// Token: 0x06000E77 RID: 3703 RVA: 0x0006BDCC File Offset: 0x00069FCC
		private void RefreshDataSource_datasource_Root_SelectedPiece(ShipUpgradePieceBaseVM newDataSource)
		{
			if (this._datasource_Root_SelectedPiece != null)
			{
				this._datasource_Root_SelectedPiece.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
				this._datasource_Root_SelectedPiece.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
				this._widget_1_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_3.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1_3;
				this._datasource_Root_SelectedPiece = null;
			}
			this._datasource_Root_SelectedPiece = newDataSource;
			this._datasource_Root_SelectedPiece = this._datasource_Root.SelectedPiece;
			if (this._datasource_Root_SelectedPiece != null)
			{
				this._datasource_Root_SelectedPiece.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
				this._datasource_Root_SelectedPiece.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
				this._datasource_Root_SelectedPiece.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
				this._widget_1_1_0.IsVisible = this._datasource_Root_SelectedPiece.IsBronzeTier;
				this._widget_1_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_0;
				this._widget_1_1_1.IsVisible = this._datasource_Root_SelectedPiece.IsSilverTier;
				this._widget_1_1_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_1;
				this._widget_1_1_2.IsVisible = this._datasource_Root_SelectedPiece.IsGoldTier;
				this._widget_1_1_2.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_2;
				this._widget_1_1_3.IsVisible = this._datasource_Root_SelectedPiece.IsDiamondTier;
				this._widget_1_1_3.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1_3;
				this._widget_1_1_3.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1_3;
			}
		}

		// Token: 0x0400021F RID: 543
		private Widget _widget;

		// Token: 0x04000220 RID: 544
		private Widget _widget_0;

		// Token: 0x04000221 RID: 545
		private Widget _widget_1;

		// Token: 0x04000222 RID: 546
		private Widget _widget_1_0;

		// Token: 0x04000223 RID: 547
		private Widget _widget_1_1;

		// Token: 0x04000224 RID: 548
		private Widget _widget_1_1_0;

		// Token: 0x04000225 RID: 549
		private Widget _widget_1_1_1;

		// Token: 0x04000226 RID: 550
		private Widget _widget_1_1_2;

		// Token: 0x04000227 RID: 551
		private Widget _widget_1_1_3;

		// Token: 0x04000228 RID: 552
		private Widget _widget_2;

		// Token: 0x04000229 RID: 553
		private ShipUpgradeSlotBaseVM _datasource_Root;

		// Token: 0x0400022A RID: 554
		private ShipUpgradePieceBaseVM _datasource_Root_SelectedPiece;
	}
}
