using System;
using System.ComponentModel;
using System.Numerics;
using NavalDLC.GauntletUI.Widgets.Widgets;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace NavalDLC.GauntletUI.AutoGenerated
{
	// Token: 0x02000019 RID: 25
	public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_23_PortUpgradePiece__InheritedPrefab : PortInspectionParentWidget
	{
		// Token: 0x06000B1F RID: 2847 RVA: 0x0005721E File Offset: 0x0005541E
		public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_23_PortUpgradePiece__InheritedPrefab(UIContext context)
			: base(context)
		{
		}

		// Token: 0x06000B20 RID: 2848 RVA: 0x00057228 File Offset: 0x00055428
		public virtual void CreateWidgets()
		{
			this._widget = this;
			this._widget_0 = new NavigationScopeTargeter(base.Context);
			this._widget.AddChild(this._widget_0);
			this._widget_1 = new ButtonWidget(base.Context);
			this._widget.AddChild(this._widget_1);
			this._widget_1_0 = new PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_27_PortUpgradePieceVisuals__DependendPrefab(base.Context);
			this._widget_1.AddChild(this._widget_1_0);
			this._widget_1_0.CreateWidgets();
			this._widget_1_1 = new BrushWidget(base.Context);
			this._widget_1.AddChild(this._widget_1_1);
			this._widget_1_2 = new Widget(base.Context);
			this._widget_1.AddChild(this._widget_1_2);
			this._widget_1_2_0 = new Widget(base.Context);
			this._widget_1_2.AddChild(this._widget_1_2_0);
			this._widget_1_2_0_0 = new ValueBasedVisibilityWidget(base.Context);
			this._widget_1_2_0.AddChild(this._widget_1_2_0_0);
			this._widget_1_2_0_0_0 = new Widget(base.Context);
			this._widget_1_2_0_0.AddChild(this._widget_1_2_0_0_0);
			this._widget_1_2_0_0_1 = new ListPanel(base.Context);
			this._widget_1_2_0_0.AddChild(this._widget_1_2_0_0_1);
			this._widget_1_2_0_0_1_0 = new TextWidget(base.Context);
			this._widget_1_2_0_0_1.AddChild(this._widget_1_2_0_0_1_0);
			this._widget_1_2_0_0_1_1 = new Widget(base.Context);
			this._widget_1_2_0_0_1.AddChild(this._widget_1_2_0_0_1_1);
		}

		// Token: 0x06000B21 RID: 2849 RVA: 0x000573BD File Offset: 0x000555BD
		public virtual void SetIds()
		{
			this._widget_1.Id = "PieceButton";
			this._widget_1_0.SetIds();
		}

		// Token: 0x06000B22 RID: 2850 RVA: 0x000573DC File Offset: 0x000555DC
		public virtual void SetAttributes()
		{
			base.WidthSizePolicy = 0;
			base.HeightSizePolicy = 0;
			base.SuggestedWidth = 70f;
			base.SuggestedHeight = 70f;
			this._widget_0.ScopeID = "UpgradePieceScope";
			this._widget_0.ScopeParent = this._widget_1;
			this._widget_0.DoNotAutoGainNavigationOnInit = true;
			this._widget_1.DoNotPassEventsToChildren = true;
			this._widget_1.UpdateChildrenStates = true;
			this._widget_1.WidthSizePolicy = 1;
			this._widget_1.HeightSizePolicy = 1;
			this._widget_1.Brush = base.Context.GetBrush("Port.Slot.Button.SoundBrush.Gold");
			this._widget_1.GamepadNavigationIndex = 0;
			this._widget_1_0.SetAttributes();
			this._widget_1_1.WidthSizePolicy = 0;
			this._widget_1_1.HeightSizePolicy = 0;
			this._widget_1_1.SuggestedWidth = 10f;
			this._widget_1_1.SuggestedHeight = 10f;
			this._widget_1_1.HorizontalAlignment = 2;
			this._widget_1_1.VerticalAlignment = 0;
			this._widget_1_1.MarginRight = 3f;
			this._widget_1_1.MarginTop = 3f;
			this._widget_1_1.Brush = base.Context.GetBrush("Port.Slot.Notification");
			this._widget_1_1.UseGlobalTimeForAnimation = true;
			this._widget_1_2.UpdateChildrenStates = true;
			this._widget_1_2.WidthSizePolicy = 1;
			this._widget_1_2.HeightSizePolicy = 1;
			this._widget_1_2_0.UpdateChildrenStates = true;
			this._widget_1_2_0.WidthSizePolicy = 1;
			this._widget_1_2_0.HeightSizePolicy = 1;
			this._widget_1_2_0_0.UpdateChildrenStates = true;
			this._widget_1_2_0_0.WidthSizePolicy = 1;
			this._widget_1_2_0_0.HeightSizePolicy = 1;
			this._widget_1_2_0_0.IndexToBeVisible = 0;
			this._widget_1_2_0_0.WatchType = 1;
			this._widget_1_2_0_0_0.WidthSizePolicy = 1;
			this._widget_1_2_0_0_0.HeightSizePolicy = 0;
			this._widget_1_2_0_0_0.SuggestedHeight = 30f;
			this._widget_1_2_0_0_0.MarginLeft = 3f;
			this._widget_1_2_0_0_0.MarginRight = 3f;
			this._widget_1_2_0_0_0.MarginTop = 3f;
			this._widget_1_2_0_0_0.VerticalAlignment = 0;
			this._widget_1_2_0_0_0.Sprite = base.Context.SpriteData.GetSprite("StdAssets\\Popup\\canvas_gradient");
			this._widget_1_2_0_0_0.Color = new Color(0f, 0f, 0f, 1f);
			this._widget_1_2_0_0_0.VerticalFlip = true;
			this._widget_1_2_0_0_1.UpdateChildrenStates = true;
			this._widget_1_2_0_0_1.WidthSizePolicy = 2;
			this._widget_1_2_0_0_1.HeightSizePolicy = 2;
			this._widget_1_2_0_0_1.HorizontalAlignment = 2;
			this._widget_1_2_0_0_1.VerticalAlignment = 0;
			this._widget_1_2_0_0_1.MarginRight = 2f;
			this._widget_1_2_0_0_1.MarginTop = 2f;
			this._widget_1_2_0_0_1_0.WidthSizePolicy = 2;
			this._widget_1_2_0_0_1_0.HeightSizePolicy = 2;
			this._widget_1_2_0_0_1_0.Brush = base.Context.GetBrush("Port.Ship.Price.Text");
			this._widget_1_2_0_0_1_1.WidthSizePolicy = 0;
			this._widget_1_2_0_0_1_1.HeightSizePolicy = 0;
			this._widget_1_2_0_0_1_1.SuggestedWidth = 16f;
			this._widget_1_2_0_0_1_1.SuggestedHeight = 16f;
			this._widget_1_2_0_0_1_1.VerticalAlignment = 1;
			this._widget_1_2_0_0_1_1.Sprite = base.Context.SpriteData.GetSprite("General\\Icons\\Coin@2x");
		}

		// Token: 0x06000B23 RID: 2851 RVA: 0x00057760 File Offset: 0x00055960
		public virtual void DestroyDataSource()
		{
			if (this._datasource_Root != null)
			{
				this._widget_1_0.DestroyDataSource();
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget_1.EventFire -= this.EventListenerOf_widget_1;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1;
				this._widget_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._datasource_Root = null;
			}
		}

		// Token: 0x06000B24 RID: 2852 RVA: 0x00057D61 File Offset: 0x00055F61
		public virtual void SetDataSource(ShipUpgradePieceBaseVM dataSource)
		{
			this.RefreshDataSource_datasource_Root(dataSource);
		}

		// Token: 0x06000B25 RID: 2853 RVA: 0x00057D6A File Offset: 0x00055F6A
		private void EventListenerOf_widget(Widget widget, string commandName, object[] args)
		{
			if (commandName == "HoverBegin")
			{
				this._datasource_Root.ExecuteInspectBegin();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root.ExecuteInspectEnd();
			}
		}

		// Token: 0x06000B26 RID: 2854 RVA: 0x00057D9C File Offset: 0x00055F9C
		private void EventListenerOf_widget_1(Widget widget, string commandName, object[] args)
		{
			if (commandName == "Click")
			{
				this._datasource_Root.ExecuteSelect();
			}
			if (commandName == "HoverBegin")
			{
				this._datasource_Root.ExecuteInspectBegin();
			}
			if (commandName == "HoverEnd")
			{
				this._datasource_Root.ExecuteInspectEnd();
			}
		}

		// Token: 0x06000B27 RID: 2855 RVA: 0x00057DF1 File Offset: 0x00055FF1
		private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B28 RID: 2856 RVA: 0x00057DFA File Offset: 0x00055FFA
		private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B29 RID: 2857 RVA: 0x00057E03 File Offset: 0x00056003
		private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B2A RID: 2858 RVA: 0x00057E0C File Offset: 0x0005600C
		private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B2B RID: 2859 RVA: 0x00057E15 File Offset: 0x00056015
		private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B2C RID: 2860 RVA: 0x00057E1E File Offset: 0x0005601E
		private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B2D RID: 2861 RVA: 0x00057E27 File Offset: 0x00056027
		private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B2E RID: 2862 RVA: 0x00057E30 File Offset: 0x00056030
		private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B2F RID: 2863 RVA: 0x00057E39 File Offset: 0x00056039
		private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1(propertyName);
		}

		// Token: 0x06000B30 RID: 2864 RVA: 0x00057E44 File Offset: 0x00056044
		private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
		{
			if (propertyName == "IsSelected")
			{
				this._datasource_Root.IsSelected = this._widget_1.IsSelected;
				return;
			}
			if (propertyName == "IsDisabled")
			{
				this._datasource_Root.IsDisabled = this._widget_1.IsDisabled;
				return;
			}
		}

		// Token: 0x06000B31 RID: 2865 RVA: 0x00057E99 File Offset: 0x00056099
		private void PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B32 RID: 2866 RVA: 0x00057EA2 File Offset: 0x000560A2
		private void boolPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B33 RID: 2867 RVA: 0x00057EAB File Offset: 0x000560AB
		private void floatPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B34 RID: 2868 RVA: 0x00057EB4 File Offset: 0x000560B4
		private void Vec2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B35 RID: 2869 RVA: 0x00057EBD File Offset: 0x000560BD
		private void Vector2PropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B36 RID: 2870 RVA: 0x00057EC6 File Offset: 0x000560C6
		private void doublePropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B37 RID: 2871 RVA: 0x00057ECF File Offset: 0x000560CF
		private void intPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B38 RID: 2872 RVA: 0x00057ED8 File Offset: 0x000560D8
		private void uintPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B39 RID: 2873 RVA: 0x00057EE1 File Offset: 0x000560E1
		private void ColorPropertyChangedListenerOf_widget_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_1(propertyName);
		}

		// Token: 0x06000B3A RID: 2874 RVA: 0x00057EEA File Offset: 0x000560EA
		private void HandleWidgetPropertyChangeOf_widget_1_1(string propertyName)
		{
			if (propertyName == "IsVisible")
			{
				this._datasource_Root.IsUnexamined = this._widget_1_1.IsVisible;
				return;
			}
		}

		// Token: 0x06000B3B RID: 2875 RVA: 0x00057F10 File Offset: 0x00056110
		private void PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B3C RID: 2876 RVA: 0x00057F19 File Offset: 0x00056119
		private void boolPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B3D RID: 2877 RVA: 0x00057F22 File Offset: 0x00056122
		private void floatPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B3E RID: 2878 RVA: 0x00057F2B File Offset: 0x0005612B
		private void Vec2PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B3F RID: 2879 RVA: 0x00057F34 File Offset: 0x00056134
		private void Vector2PropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B40 RID: 2880 RVA: 0x00057F3D File Offset: 0x0005613D
		private void doublePropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B41 RID: 2881 RVA: 0x00057F46 File Offset: 0x00056146
		private void intPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B42 RID: 2882 RVA: 0x00057F4F File Offset: 0x0005614F
		private void uintPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B43 RID: 2883 RVA: 0x00057F58 File Offset: 0x00056158
		private void ColorPropertyChangedListenerOf_widget_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2(propertyName);
		}

		// Token: 0x06000B44 RID: 2884 RVA: 0x00057F61 File Offset: 0x00056161
		private void HandleWidgetPropertyChangeOf_widget_1_2(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsDisabled = this._widget_1_2.IsHidden;
				return;
			}
		}

		// Token: 0x06000B45 RID: 2885 RVA: 0x00057F87 File Offset: 0x00056187
		private void PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B46 RID: 2886 RVA: 0x00057F90 File Offset: 0x00056190
		private void boolPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B47 RID: 2887 RVA: 0x00057F99 File Offset: 0x00056199
		private void floatPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B48 RID: 2888 RVA: 0x00057FA2 File Offset: 0x000561A2
		private void Vec2PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B49 RID: 2889 RVA: 0x00057FAB File Offset: 0x000561AB
		private void Vector2PropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B4A RID: 2890 RVA: 0x00057FB4 File Offset: 0x000561B4
		private void doublePropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B4B RID: 2891 RVA: 0x00057FBD File Offset: 0x000561BD
		private void intPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B4C RID: 2892 RVA: 0x00057FC6 File Offset: 0x000561C6
		private void uintPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B4D RID: 2893 RVA: 0x00057FCF File Offset: 0x000561CF
		private void ColorPropertyChangedListenerOf_widget_1_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0(propertyName);
		}

		// Token: 0x06000B4E RID: 2894 RVA: 0x00057FD8 File Offset: 0x000561D8
		private void HandleWidgetPropertyChangeOf_widget_1_2_0(string propertyName)
		{
			if (propertyName == "IsHidden")
			{
				this._datasource_Root.IsSelected = this._widget_1_2_0.IsHidden;
				return;
			}
		}

		// Token: 0x06000B4F RID: 2895 RVA: 0x00057FFE File Offset: 0x000561FE
		private void PropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B50 RID: 2896 RVA: 0x00058007 File Offset: 0x00056207
		private void boolPropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B51 RID: 2897 RVA: 0x00058010 File Offset: 0x00056210
		private void floatPropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B52 RID: 2898 RVA: 0x00058019 File Offset: 0x00056219
		private void Vec2PropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B53 RID: 2899 RVA: 0x00058022 File Offset: 0x00056222
		private void Vector2PropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B54 RID: 2900 RVA: 0x0005802B File Offset: 0x0005622B
		private void doublePropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B55 RID: 2901 RVA: 0x00058034 File Offset: 0x00056234
		private void intPropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B56 RID: 2902 RVA: 0x0005803D File Offset: 0x0005623D
		private void uintPropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B57 RID: 2903 RVA: 0x00058046 File Offset: 0x00056246
		private void ColorPropertyChangedListenerOf_widget_1_2_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0(propertyName);
		}

		// Token: 0x06000B58 RID: 2904 RVA: 0x0005804F File Offset: 0x0005624F
		private void HandleWidgetPropertyChangeOf_widget_1_2_0_0(string propertyName)
		{
			if (propertyName == "IndexToWatch")
			{
				this._datasource_Root.Price = this._widget_1_2_0_0.IndexToWatch;
				return;
			}
		}

		// Token: 0x06000B59 RID: 2905 RVA: 0x00058075 File Offset: 0x00056275
		private void PropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B5A RID: 2906 RVA: 0x0005807E File Offset: 0x0005627E
		private void boolPropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B5B RID: 2907 RVA: 0x00058087 File Offset: 0x00056287
		private void floatPropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B5C RID: 2908 RVA: 0x00058090 File Offset: 0x00056290
		private void Vec2PropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B5D RID: 2909 RVA: 0x00058099 File Offset: 0x00056299
		private void Vector2PropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B5E RID: 2910 RVA: 0x000580A2 File Offset: 0x000562A2
		private void doublePropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B5F RID: 2911 RVA: 0x000580AB File Offset: 0x000562AB
		private void intPropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B60 RID: 2912 RVA: 0x000580B4 File Offset: 0x000562B4
		private void uintPropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B61 RID: 2913 RVA: 0x000580BD File Offset: 0x000562BD
		private void ColorPropertyChangedListenerOf_widget_1_2_0_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
		{
			this.HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(propertyName);
		}

		// Token: 0x06000B62 RID: 2914 RVA: 0x000580C6 File Offset: 0x000562C6
		private void HandleWidgetPropertyChangeOf_widget_1_2_0_0_1_0(string propertyName)
		{
			if (propertyName == "IntText")
			{
				this._datasource_Root.Price = this._widget_1_2_0_0_1_0.IntText;
				return;
			}
		}

		// Token: 0x06000B63 RID: 2915 RVA: 0x000580EC File Offset: 0x000562EC
		private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B64 RID: 2916 RVA: 0x000580FA File Offset: 0x000562FA
		private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B65 RID: 2917 RVA: 0x00058109 File Offset: 0x00056309
		private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B66 RID: 2918 RVA: 0x00058118 File Offset: 0x00056318
		private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B67 RID: 2919 RVA: 0x00058127 File Offset: 0x00056327
		private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B68 RID: 2920 RVA: 0x00058136 File Offset: 0x00056336
		private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B69 RID: 2921 RVA: 0x00058145 File Offset: 0x00056345
		private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B6A RID: 2922 RVA: 0x00058154 File Offset: 0x00056354
		private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B6B RID: 2923 RVA: 0x00058163 File Offset: 0x00056363
		private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
		{
			this.HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
		}

		// Token: 0x06000B6C RID: 2924 RVA: 0x00058174 File Offset: 0x00056374
		private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
		{
			if (propertyName == "IsSelected")
			{
				this._widget_1.IsSelected = this._datasource_Root.IsSelected;
				this._widget_1_2_0.IsHidden = this._datasource_Root.IsSelected;
				return;
			}
			if (propertyName == "IsDisabled")
			{
				this._widget_1.IsDisabled = this._datasource_Root.IsDisabled;
				this._widget_1_2.IsHidden = this._datasource_Root.IsDisabled;
				return;
			}
			if (propertyName == "IsUnexamined")
			{
				this._widget_1_1.IsVisible = this._datasource_Root.IsUnexamined;
				return;
			}
			if (propertyName == "Price")
			{
				this._widget_1_2_0_0.IndexToWatch = this._datasource_Root.Price;
				this._widget_1_2_0_0_1_0.IntText = this._datasource_Root.Price;
				return;
			}
		}

		// Token: 0x06000B6D RID: 2925 RVA: 0x00058254 File Offset: 0x00056454
		private void RefreshDataSource_datasource_Root(ShipUpgradePieceBaseVM newDataSource)
		{
			if (this._datasource_Root != null)
			{
				this._widget_1_0.SetDataSource(null);
				this._datasource_Root.PropertyChanged -= this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.EventFire -= this.EventListenerOf_widget;
				this._widget_1.EventFire -= this.EventListenerOf_widget_1;
				this._widget_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_1.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_1;
				this._widget_1_2.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0_1_0.PropertyChanged -= this.PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.boolPropertyChanged -= this.boolPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.floatPropertyChanged -= this.floatPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.Vec2PropertyChanged -= this.Vec2PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.Vector2PropertyChanged -= this.Vector2PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.doublePropertyChanged -= this.doublePropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.intPropertyChanged -= this.intPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.uintPropertyChanged -= this.uintPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.ColorPropertyChanged -= this.ColorPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._datasource_Root = null;
			}
			this._datasource_Root = newDataSource;
			if (this._datasource_Root != null)
			{
				this._datasource_Root.PropertyChanged += this.ViewModelPropertyChangedListenerOf_datasource_Root;
				this._datasource_Root.PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(this.ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(this.ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(this.ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(this.ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(this.ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(this.ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(this.ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
				this._datasource_Root.PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(this.ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
				this._widget.EventFire += this.EventListenerOf_widget;
				this._widget_1.IsSelected = this._datasource_Root.IsSelected;
				this._widget_1.IsDisabled = this._datasource_Root.IsDisabled;
				this._widget_1.EventFire += this.EventListenerOf_widget_1;
				this._widget_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1;
				this._widget_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1;
				this._widget_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1;
				this._widget_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1;
				this._widget_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1;
				this._widget_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1;
				this._widget_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1;
				this._widget_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1;
				this._widget_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1;
				this._widget_1_1.IsVisible = this._datasource_Root.IsUnexamined;
				this._widget_1_1.PropertyChanged += this.PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_1;
				this._widget_1_1.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_1;
				this._widget_1_2.IsHidden = this._datasource_Root.IsDisabled;
				this._widget_1_2.PropertyChanged += this.PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_2;
				this._widget_1_2_0.IsHidden = this._datasource_Root.IsSelected;
				this._widget_1_2_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_2_0;
				this._widget_1_2_0_0.IndexToWatch = this._datasource_Root.Price;
				this._widget_1_2_0_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_2_0_0;
				this._widget_1_2_0_0_1_0.IntText = this._datasource_Root.Price;
				this._widget_1_2_0_0_1_0.PropertyChanged += this.PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.boolPropertyChanged += this.boolPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.floatPropertyChanged += this.floatPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.Vec2PropertyChanged += this.Vec2PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.Vector2PropertyChanged += this.Vector2PropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.doublePropertyChanged += this.doublePropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.intPropertyChanged += this.intPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.uintPropertyChanged += this.uintPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_2_0_0_1_0.ColorPropertyChanged += this.ColorPropertyChangedListenerOf_widget_1_2_0_0_1_0;
				this._widget_1_0.SetDataSource(this._datasource_Root);
			}
		}

		// Token: 0x040001B5 RID: 437
		private PortInspectionParentWidget _widget;

		// Token: 0x040001B6 RID: 438
		private NavigationScopeTargeter _widget_0;

		// Token: 0x040001B7 RID: 439
		private ButtonWidget _widget_1;

		// Token: 0x040001B8 RID: 440
		private PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_27_PortUpgradePieceVisuals__DependendPrefab _widget_1_0;

		// Token: 0x040001B9 RID: 441
		private BrushWidget _widget_1_1;

		// Token: 0x040001BA RID: 442
		private Widget _widget_1_2;

		// Token: 0x040001BB RID: 443
		private Widget _widget_1_2_0;

		// Token: 0x040001BC RID: 444
		private ValueBasedVisibilityWidget _widget_1_2_0_0;

		// Token: 0x040001BD RID: 445
		private Widget _widget_1_2_0_0_0;

		// Token: 0x040001BE RID: 446
		private ListPanel _widget_1_2_0_0_1;

		// Token: 0x040001BF RID: 447
		private TextWidget _widget_1_2_0_0_1_0;

		// Token: 0x040001C0 RID: 448
		private Widget _widget_1_2_0_0_1_1;

		// Token: 0x040001C1 RID: 449
		private ShipUpgradePieceBaseVM _datasource_Root;
	}
}
